### ISSUE TITLE
Continues to say "Notifications are OFF" after turning it on

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-shield-mobile#161]
The app continues to say "Notifications are off" after turning it on. The button in the menu to turn on notifications goes away after turning it on.'

![image](https://user-images.githubusercontent.com/63243608/85652268-36cda900-b678-11ea-80c1-eb7dd80dd733.png)

**Comment by timarney** [comment]
https://github.com/CovidShield/mobile/pull/160

**Comment by timarney** [comment]
Closed https://github.com/cds-snc/covid-shield-mobile/pull/170

There's another case we need to look into - what happens if after the "happy path" the user turns off notifications manually.  

Closing this as it handles the flow described.

**Comment by timarney** [comment]
> There's another case we need to look into - what happens if after the "happy path" the user turns off notifications manually.

https://github.com/CovidShield/mobile/issues/163
