### ISSUE TITLE
Missing the prompt from iOS to turn on notifications

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-shield-mobile#164]
Expected behavior: after onboarding the system prompts the user to turn on logging and then another prompt to turn on notifications.

Actual behavior: after onboarding the system prompts the user to turn on logging. The user is never prompted to turn on notifications. The menu panel indicates that notifications are off.

This has been tested on iOS, not Android.

**Comment by timarney** [comment]
@Stephen-PM can you confirm this on the latest build(s)

**Comment by JuliannaR** [comment]
This has been fixed.
