### ISSUE TITLE
Missing padding on top of "No 8-digit number?" page

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#209]
Environments : 
Galaxy S7 Android v6 on BrowserStack (apk)

Scenario : 
- Open app
- Open "Covid alert is off" menu
- Click on "Diagnosed with covid-19?"
- Click on "No 8-digit number?"

Issue : 
Seems like some padding is missing on the top of the screen so it looks like the "back" button is touching the notification bar of the phone

![bs_realdroid_Mobile_Samsung Galaxy S7-6 0-1440x2560](https://user-images.githubusercontent.com/47008295/85893929-a2af2f00-b7a8-11ea-990a-e58dcb691f87.jpg)

**Comment by JuliannaR** [comment]
@srepussard this screen has changed.
![Image from iOS (9)](https://user-images.githubusercontent.com/35537308/86498826-9b15fa00-bd55-11ea-9b45-69ab23e40a2b.png)

**Comment by srepussard** [comment]
Confirmed that the screen changed and the margin on the "Cancel/Annuler" link is big enough to avoid accidentally clicking on the bar
