### ISSUE TITLE
FR "No 8-digit number" link is left centered

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#213]
Environments : 
Android v6 on Galaxy S7 (Browserstack, apk)

Scenario : 
- Open app
- Change language to FR
- Navigate to "Enter your 8-digit number" screen

Issue : 
The link for FR "No 8-digit number" is left centered instead of being in the center of the screen like for the ENG screen

![bs_realdroid_Mobile_Samsung Galaxy S7-6 0-1440x2560 (2)](https://user-images.githubusercontent.com/47008295/85895089-d2f7cd00-b7aa-11ea-98d1-b6a18a982f2e.jpg)

**Comment by JuliannaR** [comment]
This screen now uses a nav element instead of a link. Can you confirm if I can close @srepussard

**Comment by JuliannaR** [comment]
Link is no longer displayed like this and is now a nav element.
![Image from iOS (8)](https://user-images.githubusercontent.com/35537308/86482148-5e2f1080-bd1f-11ea-8b25-c637249d50db.png)

**Comment by srepussard** [comment]
Confirmed that instead of just text, this is now replaced by a button
