### ISSUE TITLE
"No" is read as "number" with VoiceOver 

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-shield-mobile#217]
A couple of screens where it says "No 8-digit number?", VoiceOver reads "No" as "number". So it reads "Number 8-digit number" which is incorrect. 

iOS 13.5.1 on iPhone 7

![covidalert7](https://user-images.githubusercontent.com/14280062/85898101-a7380f80-b7c9-11ea-9bd2-e1eb88a095f6.jpg)
![covidalert6](https://user-images.githubusercontent.com/14280062/85898103-a7d0a600-b7c9-11ea-9cf7-ceb4b2144226.jpg)

**Comment by JuliannaR** [comment]
@katewilhelm can we re structure the wording here? VoiceOver reads "Number 8 digit number?" It's reading it as No. 8.
