### ISSUE TITLE
Notification prompt is displayed in English (iOS)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#233]
iPhone 8
French
Just downloaded the app, went through the onboarding (no province selected). chose to enable the COVID-19 Exposure logging.
focus is returned to the home screen. tapped to open the menu.
Clicked the turn on notification from menu. 
prompt is displayed in English. see screenshot.
Expected result: prompt should be in French.
![Notification prompt_EN ](https://user-images.githubusercontent.com/65728700/85924513-d64d9000-b860-11ea-9668-34e8b1a5ccbe.PNG)

**Comment by JuliannaR** [comment]
We do not have the ability to change this because it comes from the OS level, which is the language of the OS install. 
@mmiron-HC are you okay with closing this issue?

This is the similar as issue: https://github.com/cds-snc/covid-shield-mobile/issues/190

**Comment by mmiron-HC** [comment]
@JuliannaR  yes it is fine to close..
