### ISSUE TITLE
Missing padding next to > for Exposure notification button (iOS/Android)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#234]
both iPhone Xr and Galaxy S8+ (android version 9)
French
Exposure notifications = Off
app Home screen shows the Exposure notification button. the text seems to be overlapping with the > image.
![Samsung_spacing on button](https://user-images.githubusercontent.com/65728700/85926681-0d2aa280-b86f-11ea-817f-fdf16d1bc7d0.jpg)
![iphone_notification spacing issues](https://user-images.githubusercontent.com/65728700/85926682-0dc33900-b86f-11ea-9bc4-d3bd2378dd7b.png)
Note that the Android has different font settings on the phone.

**Comment by JuliannaR** [comment]
@mmiron-HC can you confirm if this is still an issue? Phones have the ability to change font and size, we are hoping to ensure things work properly up to 200% font increase or zoom/magnification.

**Comment by mtropper** [comment]
The text seems to be considerably reduced. 
![image](https://user-images.githubusercontent.com/52504483/87058417-0f2d2380-c1d6-11ea-92c1-3abf635c244e.png)

**Comment by JuliannaR** [comment]
@mmiron-HC could you review please? Thanks!

**Comment by JuliannaR** [comment]
Thanks @mtropper. The text was changed on this screen to be shorter.

**Comment by mmiron-HC** [comment]
confirmed
