### ISSUE TITLE
Word wrapping - "Précédent" button on "How COVID Alert works" in FR - (iOS/Android)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#235]
both iPhone 8 and galaxy S8+ (v9) have this issue.
language = French
from the menu, selected the "How COVID Alert works" option. 
Clicked Next
the word "Précédent" wraps and it shouldn't
![word wrapping Galaxy8](https://user-images.githubusercontent.com/65728700/85926915-92fb1d80-b870-11ea-96ee-8329bd85d3a7.jpg)
![text wrapping_iphone8](https://user-images.githubusercontent.com/65728700/85926916-9393b400-b870-11ea-9cca-bc8b296f871a.png)

**Comment by JuliannaR** [comment]
@timarney @smcmurtry how are we addressing responsive design in the app? Given the screen resolutions across the phones that can be used is pretty wide ranging and the features of phones enable large text, zoom and magnification, is there a way to address this meaningfully?

**Comment by nickmly** [comment]
This doesn't seem to happen anymore on iPhone 8, @mmiron-HC or @JuliannaR can you confirm?
![Simulator Screen Shot - iPhone 8 - 2020-07-04 at 10 30 13](https://user-images.githubusercontent.com/5861415/86514683-694a7500-bde1-11ea-8927-a0e2520e42aa.png)

**Comment by JuliannaR** [comment]
Currently the app supports text magnification of 200%. Above 200% and the user will encounter this. @mmiron-HC I think we can close this one as it functions to WCAG requirement of screen zoom.

![Image from iOS (11)](https://user-images.githubusercontent.com/35537308/86515629-58e9c880-bde8-11ea-8be5-77c0815fea1c.png)

![Image from iOS (10)](https://user-images.githubusercontent.com/35537308/86515625-55eed800-bde8-11ea-808f-16db7e200119.png)
