### ISSUE TITLE
Enable COVID-19 Exposure prompt displayed in EN when in FR (iOS)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#237]
iPhone XR and iPhone 8
Newly download. 
Selected FR as language and went through the onboarding screens - clicked done.
From where are you located - I clicked Skip
prompted with the Enable COVID-19 Exposure Logging and notification pop up Text displayed is EN.
Expected result: should be in FR.
![iphone_Enable Expo prompt in EN](https://user-images.githubusercontent.com/65728700/85927724-eae85300-b875-11ea-8d4a-9bf8ad9f3ef9.png)

**Comment by timarney** [comment]
Will need to confirm once this PR is merged

https://github.com/cds-snc/covid-shield-mobile/pull/311

**Comment by JuliannaR** [comment]
We should reconsider our experience because the language impacts can potentially by confusing. @katewilhelm and @EliseKa can we have a conversation about this? We cannot change the language of the OS prompt and the pathway can introduce multiple language screens connected.

**Comment by JuliannaR** [comment]
this is the OS language setting.
