### ISSUE TITLE
Page not read properly by TalkBalk [Android]

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-shield-mobile#247]
A few issues with COVID Alert menu.

1) TalkBack is not reading all content on the page. Tried with "Read from top" and tried to flick item by item.
Highlighted text in yellow is not read. 

2) The page doesn't scroll up automatically when the screen reader when TalkBack reaches the bottom of the visual page. 

3) Content below is not read by TalkBack(highlighted in yellow), unless the user is at the bottom of the page before they start reading from top

4) After reading the visual content, the content behind this popup is read ("Exposure messages are off" etc) 

5) "Close button" is not highlighted (focus) at the correct location.

Samsung Android version 8.1.0

![111](https://user-images.githubusercontent.com/14280062/85936329-9a99e100-b8c7-11ea-8882-0be353daebd3.jpg)
![11](https://user-images.githubusercontent.com/14280062/85936330-9a99e100-b8c7-11ea-8837-5fafc0bd14f4.jpg)
![1](https://user-images.githubusercontent.com/14280062/85936331-9b327780-b8c7-11ea-9cc9-3bc482ef3cb7.jpg)

**Comment by timarney** [comment]
@henrytao-me - I believe this will be related to the bottom drawer issue.

**Comment by timarney** [comment]
https://github.com/cds-snc/covid-shield-mobile/issues/269

**Comment by henrytao-me** [comment]
I can take it too

**Comment by JuliannaR** [comment]
Merged into this issue: https://github.com/cds-snc/covid-shield-mobile/issues/432
