### ISSUE TITLE
Provinces/language are read as radio buttons with VoiceOver and TalkBack 

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-shield-mobile#249]
Provinces and language pages are read as radio buttons with both VoiceOver and TalkBack while they're not visually radio buttons. When radio buttons are done, they announce radio button # of 13 or # of 2 but they're not. These shouldn't be coded as radio buttons

Android 8.1.0 on Samsung 
iOS 13.5.1 on iPhone 7

![1](https://user-images.githubusercontent.com/14280062/85937030-c324d980-b8cd-11ea-85bf-1a22a5cee030.jpg)
![2](https://user-images.githubusercontent.com/14280062/85937032-c324d980-b8cd-11ea-93d3-d364219ae659.jpg)

**Comment by JuliannaR** [comment]
@qanitah these are designed as radio buttons although they look differently, the function by allowing only one selection at a time.
