### ISSUE TITLE
Delay in rendering screens when rotating (Android)

### ISSUE THREAD

**Issue by sarasuri** [cds-snc/covid-shield-mobile#253]
Scenario

Samsung Galaxy J3 Prime 
Android version 7.0

When rotates the device between portrait/landscape orientation there is a delay in screen rendering before it goes to the proper screen display.

Screenshots
![landscape](https://user-images.githubusercontent.com/12256067/85947907-854ea200-b91b-11ea-8837-1c8b0cb8cebb.gif)
![port](https://user-images.githubusercontent.com/12256067/85947910-87b0fc00-b91b-11ea-8483-66c2eadb3805.gif)

**Comment by JuliannaR** [comment]
connected to this issue upstream https://github.com/CovidShield/mobile/issues/11

**Comment by smcmurtry** [comment]
We locked to portrait mode in #297
