### ISSUE TITLE
Menu: Exposure Notifications are off messages for Android and iOS are different 

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#254]
iPhone Xr and Samsung Galaxy S8+ (Android v9)
Exposure Notifications are off
Notifications are off

open the menu, the message is different for Exposure notifications in the iphone vs Android. 
they should be the same.
![iphone_menu_ExpNotif off](https://user-images.githubusercontent.com/65728700/85947971-fdb56300-b91b-11ea-9ed5-9b6185dccc8e.png)
![Android_Menu_expNotifications off](https://user-images.githubusercontent.com/65728700/85947972-fe4df980-b91b-11ea-848b-ad340a222ae0.jpg)

**Comment by JuliannaR** [comment]
This should be corrected on the latest build. @mmiron-HC I'll look to get you an invite to the android build that's in the playstore to confirm.

**Comment by JuliannaR** [comment]
@mmiron-HC now that you are on the playstore install, using yesterdays version, can you confirm this is okay to close?

**Comment by mmiron-HC** [comment]
@JuliannaR this is no longer an issue now that we understand that Google has lumped the push notifications within its "Turn on exposure notifications" prompt. so it makes sense that iOS has two different messages when android only has one.
