### ISSUE TITLE
Menu: Change Province or territory in FR is incorrect

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#255]
iphone 8/XR and samsung Galaxy S8+
in French
open menu
the label for the Change province or territory in french should be "Modifier la province ou le territoire" (as per figma)
![image](https://user-images.githubusercontent.com/65728700/85948353-71586f80-b91e-11ea-991f-7010027fc0b2.png)

**Comment by EliseKa** [comment]
created PR #327 to fix this issue
