### ISSUE TITLE
Menu: Android does not display notifications are off when COVID Alert is OFF

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#257]
Android v9 and 8
samsung Galaxy S8+ and OnePlus 7
- COVID-19 Exposure logging = off
- Bluetooth : Off
- Notifications : Off

1. Install the app for the first time 
2. Navigate through the Onboarding screens until the Enable COVID-19 exposure logging and notifications is displayed.
3. Click Don't Enable
4. Verify that the menu displays the following messages:  
EN: COVID Alert is OFF and Notifications are OFF 
FR:  Alerte COVID est désactivé and Notifications désactivées

iPhone displays both messages
Android does not
Notification message should be displayed like iOS.

![Android_Menu_no notifications msg](https://user-images.githubusercontent.com/65728700/85949026-39532b80-b922-11ea-9c5e-ae06a79c8d1f.jpg)

**Comment by smcmurtry** [comment]
This should now be fixed. The logic that decides when to display the warning in the collapsed bottom sheet has changed. There used to be cases where it would show up in the expanded sheet, but not in the collapsed sheet. 

There is a related issue where this content isn't updating as frequently as it needs to if you make a change via the settings screen. I will file an issue for that separately.

**Comment by JuliannaR** [comment]
@mmiron-HC can you verify that this works for you now based on @smcmurtry comment above? I sent you the link for a playstore download of the app with our meeting invite.

**Comment by timarney** [comment]
We need to push to the Play store again first :) 

Plan to see this change first thing in the A.M

**Comment by mmiron-HC** [comment]
both messages now appear tested using OnePlus 3
![Screenshot_20200709-064537](https://user-images.githubusercontent.com/65728700/87030736-09bce280-c1b0-11ea-9397-9d3ff250e712.jpg)
