### ISSUE TITLE
Home and Menu: Exposure message disappears - reappears (Android v 8 - OnePlus 3)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#259]
onePlus 3 Android version 8
Bluetooth = Off
Exposure notifications = off
notifications = off
New download on of the latest apk - dated June 27 
No province selected
Home screen initially displays the Exposure messages are off with the button to turn off notifications. Menu also shows the message (turn on exposure notifications).
If I close the app and re-open it, i see the red button appear briefly and then disappear. But in the end, the home screen shows no Exposure detected message and no message in the menu.
I've been able to repeat this a few times. 

Note that this last time, I've navigated to the settings menu to check the android version and when I returned to the app (running in background) the home screen with button was re-displayed along with the appropriate menu message. 

in the image - On the right is the one plus 3 and the left is the Samsung galaxy S8+.
![side by side androids](https://user-images.githubusercontent.com/65728700/85950961-f5662380-b92d-11ea-81ae-32486e77c53c.jpg)

**Comment by mmiron-HC** [comment]
I was able to retest this scenario using another OnePlus 6 android version 9 and it doesn't even load the Turn on exposure notifications button or the screen it goes directly to the No exposure detected screen.

**Comment by henrytao-me** [comment]
@mmiron-HC Can you verify it again? ExposeStatus is persisted after this PR https://github.com/CovidShield/mobile/pull/177. It's already merged to this repo. 🙇 

I will close this for now. Please reopen if it still happens 🙇

**Comment by mmiron-HC** [comment]
@henrytao-me  looks like it is working as expected now.
