### ISSUE TITLE
Missing padding on top of screens for "How COVID Alert works"

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#272]
Environment : 
Pixel 3XL, Android v9 (BrowserStack), version v14

Scenario : 
- Open app
- Open menu and click on "How COVID Alert works"

Issue : 
The 6 screens of this section are missing padding on top of the screen : the "back" arrow button is too close to the top and everytime I click on it, I click on the notification bar at the same time

![bs_realdroid_Mobile_Google Pixel 3 XL-9 0-1440x2960 (1)](https://user-images.githubusercontent.com/47008295/85966045-7e537e00-b973-11ea-9216-54fae950fcbe.jpg)

**Comment by mmiron-HC** [comment]
Samsung Galaxy S8+ 
arrow cannot to return. it is buried under the clock
![Android_return arrow How it works](https://user-images.githubusercontent.com/65728700/86038759-71846800-ba0f-11ea-8074-9f174dce6d38.jpg)

**Comment by jelen-HC** [comment]
I am having the same issue on the Samsung Galaxy S6. I just tested this after the latest apk release this morning and am unable to interact with the top left back button due to it being to close to the device status bar.

**Comment by timarney** [comment]
@nickmly did this get fixed yet?

**Comment by mmiron-HC** [comment]
We haven't rec'd a new apk, therefore I cannot confirm if it was fixed.

**Comment by nickmly** [comment]
@timarney This was fixed in #308 I believe

**Comment by JuliannaR** [comment]
> We haven't rec'd a new apk, therefore I cannot confirm if it was fixed.

Manon, I added an new .apk today in the tester channel

**Comment by timarney** [comment]
From the latest build in the Play store.

@JuliannaR going to mark this as fixed but won't close yet. 

![Screenshot_20200704-104921](https://user-images.githubusercontent.com/62242/86515310-fa234f80-bde5-11ea-9c16-47a7a8ac01bf.png)

**Comment by JuliannaR** [comment]
Thanks for fixing the padding. @amazingphilippe might want to address the icon. Do we have control to make it consistent with the IOS version? We use close for actions that end, and back for actions to move in the nav. Thoughts?

**Comment by JuliannaR** [comment]
The touch area is now fixed.

**Comment by srepussard** [comment]
Tested on Pixel 3a, Android 10, v25 from Play Store : **Passed**
- This has been fixed. The arrow is now replaced by "Close/Fermer" and the margin has been fixed so we don't accidentally click the bar anymore

![Screenshot (Jul  7, 2020 15_13_21)](https://user-images.githubusercontent.com/47008295/86849610-c99d1900-c064-11ea-9c53-1835394316c3.png)
