### ISSUE TITLE
"Share your random codes" notification - Screen in background on infinite load state

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#273]
Environment : 
Pixel 3XL, Android v9 (BrowserStack), version v14

Scenario : 
- Go to Enter you code screen from the menu
- Enter a 8-digit code and submit
- Click on "Agree" on the upload code screen

Expected : 
A notification about "share you random codes" is displayed on top of the upload code screen

Issue : 
The screen in the background of the notification is on an infinite load state

![bs_realdroid_Mobile_Google Pixel 3 XL-9 0-1440x2960 (3)](https://user-images.githubusercontent.com/47008295/85966981-2ff3ae80-b976-11ea-99fd-d505b802cb61.jpg)

**Comment by jpeersoxd** [comment]
On Android 8.1 I am seeing the same thing, except I don't get a message about sharing my ID. Cannot progress past this point.

<img width="340" alt="Screen Shot 2020-07-02 at 8 00 56 AM" src="https://user-images.githubusercontent.com/65189530/86375140-2dc17680-bc3a-11ea-865a-e3e031ba5365.png">

**Comment by jpeersoxd** [comment]
Attaching log file
[app-release.apk_2020_7_2_15_5_54.log](https://github.com/cds-snc/covid-shield-mobile/files/4865136/app-release.apk_2020_7_2_15_5_54.log)

**Comment by JuliannaR** [comment]
Can you prioritize this in your workflow with someone?

**Comment by smcmurtry** [comment]
We are putting up a loading spinner here while the user answers the permission popup. The spinner goes away once the popup is answered. What specifically is the problem with that?

@jpeersoxd it sounds like your issue is not related to the loading spinner and should be filed as a separate issue if you are still experiencing it.

**Comment by timarney** [comment]
@JuliannaR per @smcmurtry 

> We are putting up a loading spinner here while the user answers the permission popup. The spinner goes away once the popup is answered. What specifically is the problem with that?

**Comment by JuliannaR** [comment]
I think this is a non issue, because when selected share this goes away. @srepussard I am going to close this as it works as expected.

**Comment by jpeersoxd** [comment]
@JuliannaR Please reopen this. I have just retested with today's codes, and there is no permission popup coming up. I only have the spinner, and no way of proceeding from there. I tried killing/restarting the app, which then takes me to the upload your random codes screen. When I click to upload, I again get the spinner with no permission popup.

**Comment by JuliannaR** [comment]
@jpeersoxd It

**Comment by jrdpeers** [comment]
It seems the same to me as it’s an infinite load from that point. If dev disagrees I can open a new ticket but either way this needs attention

**Comment by timarney** [comment]
> I have just retested with today's codes, and there is no permission popup coming up. I only have the spinner, and no way of proceeding from there. I tried killing/restarting the app, which then takes me to the upload your random codes screen. When I click to upload, I again get the spinner with no permission popup.

If someone can verify this exist in the Google Play version we can have a deeper look.  I just want to take any variances out of the mix first.

**Comment by jpeersoxd** [comment]
OK, I installed from the Play Store on an S20. After inputting my code, I see this: 

<img width="340" alt="Screen Shot 2020-07-05 at 1 23 45 PM" src="https://user-images.githubusercontent.com/65189530/86541573-ce29cc00-bec2-11ea-9a75-11b22c7c52b4.png">

**Comment by timarney** [comment]
I'm getting this - Android 9 . Moto G 8

<img width="400" src="https://user-images.githubusercontent.com/62242/86541753-6fbe1700-bedd-11ea-8907-578884b27c97.png" />

**Comment by jrdpeers** [comment]
And after clicking on Agree it doesn’t go into a spin?

**Comment by timarney** [comment]
| Enter a code   | 1    | 2    | 3    |   |
|-----------|------|------|------|---|
| Submit     | <img width="300" src="https://user-images.githubusercontent.com/62242/86541753-6fbe1700-bedd-11ea-8907-578884b27c97.png"> |<img width="300" src="https://user-images.githubusercontent.com/62242/86541823-08ed2d80-bede-11ea-8ff2-5216494f7573.png"> | <img width="300" src="https://user-images.githubusercontent.com/62242/86541825-0a1e5a80-bede-11ea-8080-1c1af276c568.png"> |   |

**Comment by jpeersoxd** [comment]
I think I've finally tracked this down. The app is not working properly for me unless I update the Play Store version. Then I get the behaviour you see. We can close this.
