### ISSUE TITLE
Focus does not land at the right location (top of the screen) with VoiceOver on

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-shield-mobile#281]
With VoiceOver on, some pages don't have the focus on top of the page when the user taps on a button. Instead, the focus is somewhere middle of the page on the following screen. 

Please see screenshots of "From" screen to where the focus starts on and then see "To" screen to see where the focus lands on. Focus should always start on top of the page.

iOS 13.5.1 on iPhone 7

![9a](https://user-images.githubusercontent.com/14280062/86031922-890a2380-ba04-11ea-957e-d9377277123f.jpg)
![9b](https://user-images.githubusercontent.com/14280062/86031925-89a2ba00-ba04-11ea-978b-ed653032cf7d.jpg)

**Comment by JuliannaR** [comment]
Similar to issue https://github.com/cds-snc/covid-shield-mobile/issues/291
Focus needs to be at the top of the content, in this case the header. @nickmly @its-anirudh @smcmurtry

**Comment by timarney** [comment]
@JuliannaR can you confirm this is still an issue?

**Comment by JuliannaR** [comment]
@timarney focus when loading this page is now with the first interactive element which in this instance is cancel. Two finger gesture reads content, left and right swipe move up and down starting with the header. This is fixed.
