### ISSUE TITLE
How COVID Alert works: Heading on subsequent slides are missing (FR)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#285]
confirmed in iOS and Android.
Language = French
Viewing the How COVID Alert works link (from either the Onboarding slides or from the Menu)
navigate to 2nd step - note that the english contains a heading on subsequent step indicating the step they are on.
FR does not. 
see screenshot
![image](https://user-images.githubusercontent.com/65728700/86038211-91fff280-ba0e-11ea-9d49-4635ae922afe.jpg)

**Comment by JuliannaR** [comment]
This was fixed in V11. @mmiron-HC please let me know if I can close. The heading appears in french now. 
![Image from iOS (5)](https://user-images.githubusercontent.com/35537308/86363212-872ea300-bc44-11ea-9797-23eabf78002f.png)

**Comment by mmiron-HC** [comment]
@JuliannaR Retested and titles are now being displayed as expected in Android.
