### ISSUE TITLE
"region" is hardcoded to "ON"

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/covid-shield-mobile#286]
In the file "BackendService.ts", in "getExposureConfiguration()", the value "region" is hardcoded as a _const_ to be "ON".

**Comment by timarney** [comment]
These now get pulled from the .env based on an upstream change.  We'll want to adjust this again to use our province selector not the .env 
```
// import {TRANSMISSION_RISK_LEVEL, REGION} from 'env';
```

**Comment by timarney** [comment]
@jeberhardt going to close this as the original issue is fixed
