### ISSUE TITLE
An empty\blank focus needs to be removed in VO

### ISSUE THREAD

**Issue by paulettefrancis** [cds-snc/covid-shield-mobile#287]
Swiping using VO in iOS.

When swiping on the "How it works" onboarding page, there is an empty\blank focus that needs to be removed.

iPhone XR 13.5.1

![Snap3](https://user-images.githubusercontent.com/22638158/86047795-751eeb80-ba1d-11ea-9859-10d3e210d1b0.jpg)

**Comment by JuliannaR** [comment]
@nickmly this might be an easy one to add to your onboarding work, there is an extra focusable field that needs to be removed here.

**Comment by JuliannaR** [comment]
@smcmurtry similar to the one you fixed today.

**Comment by JuliannaR** [comment]
@paulettefrancis this will appear in V15 on IOS.

**Comment by JuliannaR** [comment]
Fixed in V16 IOS/Android
