### ISSUE TITLE
Focus doesn't go to the top of the page using VO in iOS

### ISSUE THREAD

**Issue by paulettefrancis** [cds-snc/covid-shield-mobile#291]
When landing on the "Where do you live" page, the focus goes to "New Brunswick" instead of to the top of the page.

iPhone XR 13.5.1

![image](https://user-images.githubusercontent.com/22638158/86048905-31c57c80-ba1f-11ea-8c7a-2bcc4906a9f4.png)

**Comment by JuliannaR** [comment]
@smcmurtry, @nickmly or @its-anirudh the focus on this page now goes to the skip button element, can we have this focus on the top of page/header?

**Comment by JuliannaR** [comment]
focus is set the the skip link button. It should focus on the header or top of page.

**Comment by JuliannaR** [comment]
This is fixed in V16.
