### ISSUE TITLE
"Upload new random codes" screen spelling error - v9 EN

### ISSUE THREAD

**Issue by jelen-HC** [cds-snc/covid-shield-mobile#302]
Minor issue/fix; in the second sentence, "about" is currently spelt "abouot". This was seen in version 9, so I am not sure if this has been fixed yet. Will have to put a code into the new version and wait until the next day to test this again.

**Comment by katewilhelm** [comment]
@jelen-HC Can you please share a bit more about which screen this is on? Perhaps a screen shot? Or a description of the steps you took before you saw it? Thank you!

**Comment by jelen-HC** [comment]
@katewilhelm I do not have a screen shot of this unfortunately and am not able to take one since I have already chosen the option to upload the new codes. 

Yesterday afternoon I entered one of the new exposure codes and followed the steps to have the home screen change to the "Thanks for helping fight COVID" message; "For the next 14 days, you'll get a daily notification asking permission to upload any new random codes your phone sent".

I left my phone in this state overnight to see if I would get the prompt the next day (Which is today). When I opened the app today I was indeed confronted with the main/home screen now displaying "Upload new random codes" with two sentences providing information about this and then the button to upload new codes. It is in the second sentence that "about" is spelt "abouot".

Hopefully this helps to clarify a bit more.

**Comment by katewilhelm** [comment]
Excellent thank you!

**Comment by katewilhelm** [comment]
Fixed English in pull request #306. @EliseKa can you please check that the French is up to date? This screen has gone through many iterations. I'll tag you in figma on the one we need

**Comment by katewilhelm** [comment]
this is how it should look <img width="573" alt="Screen Shot 2020-06-30 at 10 24 36 AM" src="https://user-images.githubusercontent.com/57191279/86138091-fcbb3780-babb-11ea-9d6e-669058c524c0.png">
