### ISSUE TITLE
"Turn on exposure notifications" prompt not displayed when using swipe

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#316]
Environment : 
Pixel 3a, Android 10, apk v15.a

Scenario : 
- Install the app
- From onboarding screens, navigate to the screen "The app will now ask your permission"
- Don't click on "Next" but swipe left to get to the next screen

Expected : 
The screen "Choose your province or territory" should be displayed with a prompt on top asking you to turn on exposure notifications

Issue : 
The prompt is not displayed when swiping from the previous page but it is displayed when we click on "Next" from the previous screen

**Comment by smcmurtry** [comment]
Closed by #310

**Comment by srepussard** [comment]
Tested on Pixel 3a, Android 10, v25 from Play Store : **Passed**
- Swipe functionality has been removed from onboarding screens so this issue is not happening anymore
