### ISSUE TITLE
Content is not read in correct order when moving from screen 4 to 5 with Talkback

### ISSUE THREAD

**Issue by sarasuri** [cds-snc/covid-shield-mobile#317]
Scenario to reproduce

Samsung Galaxy J3 Prime
Android version 7.0

Step 1 to 6 screens after splash screen

While Talkback is on, swiping right to move to next element on the screens from Step 1, Talkback moves to each screen and continue reading. When it moves to step 5 screen “The app will now ask your permission”, it announces “The app uses Bluetooth to exchange random …” which is from the previous screen. When continue swiping the focus goes to “Français” button and read from there.

Expected result
Talkback should read the heading of the step 5 screen like it was reading for other screens.

WCAG
https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html

Screenshots
![screen5b](https://user-images.githubusercontent.com/12256067/86148713-faaba580-bac8-11ea-8853-816644112dd1.gif)
![screen5a](https://user-images.githubusercontent.com/12256067/86149106-81608280-bac9-11ea-9b99-528f55f11c33.gif)

**Comment by qanitah** [comment]
The same behaviour for Samsung Android version 8.

**Comment by nickmly** [comment]
This seems to be an issue with the `BulletPointX` component on the `Anonymous` view in Onboarding. Looking into it

**Comment by JuliannaR** [comment]
The good news, I can access all the content in VoiceOver in this update. There is an issue though, the focus when you go from screen to screen is on the button and not the heading, can we fix that @nickmly

**Comment by JuliannaR** [comment]
This is fixed in your latest PR around onboarding flows. @smcmurtry the screen has changed a lot but the reading order was addressed re: page nav. Can you confirm and we can close?

**Comment by smcmurtry** [comment]
Yes my pr #398 fixed this issue
