### ISSUE TITLE
"Push notifications for COVID Alert" not showing at all on Android

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#319]
Environment : 
Pixel 3a, Android 10, apk v15-a

Scenario : 
- Install the app
- Navigate the onboarding screens until "Choose your province" screen
- Click on "Turn on" for the "Turn on exposure notifications" prompt

Expected : 
A second prompt to allow "Push notifications for COVID Alert" should have been displayed

Issue : 
The prompt for "Push notifications for COVID Alert" never showed up on Android (phone notifications being ON or OFF)

**Comment by timarney** [comment]
@dsamojlenko 
Possibly related?
https://github.com/CovidShield/mobile/issues/114#issuecomment-642954453

**Comment by smcmurtry** [comment]
I think this is getting set in the background without the need for a popup. Correct me if I'm wrong @henrytao-me.

**Comment by timarney** [comment]
https://github.com/cds-snc/covid-shield-mobile/issues/271

**Comment by henrytao-me** [comment]
Android doesn't require permission to show push notification. That's why it's not relevant / shows up in Android. 

I think we can close this issue.

**Comment by JuliannaR** [comment]
@srepussard I'm closing this based on @henrytao-me comment on android functionality, if you have follow up please reach out.

**Comment by srepussard** [comment]
Thank you for the investigation. I'll edit the test cases to adapt to this behavior.
