### ISSUE TITLE
Select province screen - Missing part of ENG content

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#320]
Environment : 
Pixel 3a, Android 10, apk v15-a

Scenario : 
- Set language as ENG
- From the menu, select "Change province"

Expected : 
Content above selector should be : 
"Choose the province or territory whose public health guidance you need to follow.
This information is only stored on your phone and will never be shared with anyone"

Issue : 
For the ENG language screens, the first paragraph is missing : "Choose the province or territory whose public health guidance you need to follow."
Note that in the FR language screen, the 2 paragraphs are there.

![Screenshot (Jun  30, 2020 09_29_02)](https://user-images.githubusercontent.com/47008295/86152458-09885d00-bab5-11ea-9520-65deeecb7e06.png)

**Comment by timarney** [comment]
@katewilhelm I added the text above as a placeholder - what copy to we want there?

**Comment by its-anirudh** [comment]
I added this "Choose the province or territory whose public health guidance you need to follow." 
https://github.com/cds-snc/covid-shield-mobile/pull/326

**Comment by katewilhelm** [comment]
I'm still working on this. Will I be able to add it myself to JSON file?
