### ISSUE TITLE
Missing padding above "Back" button on FR "How COVID Alert works" screens

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#321]
Environment : 
Pixel 3a, Android 10, apk v15-a

Scenario : 
- From onboarding, select FR language
- Navigate to the "Fonctionnement" screen and click on the link "En savoir plus sur le fonctionnement"

Issue : 
Missing padding above "Back" button on FR "How COVID Alert works" screens. This hinders users from clicking on the button as it's too close to the notification bar.
Note that this is only happening for FR screens.

![Screenshot_20200630-084336](https://user-images.githubusercontent.com/47008295/86153020-deead400-bab5-11ea-9b59-35f3146c2a1a.png)

**Comment by nickmly** [comment]
I think this issue is fixed with the new smaller images and margins: 
![Screenshot_1593541129](https://user-images.githubusercontent.com/5861415/86162349-a1e60800-badc-11ea-8681-0877ddf02d95.png)


I am using a Pixel 3a simulator and I can hit the back button

**Comment by srepussard** [comment]
Tested on Pixel 3a, Android 10, v25 from Play Store : **Passed**
- This has been fixed. "Fermer" is now replacing the arrow and the margin has been fixed

![Screenshot (Jul  7, 2020 15_13_21)](https://user-images.githubusercontent.com/47008295/86849472-9064a900-c064-11ea-8418-64940817d766.png)
