### ISSUE TITLE
Extra padding in Menu when "Notifications are off"

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#322]
Environment : 
Pixel 3a, Android 10, apk v15-a

Scenario : 
- Set your notifications as OFF
- Open app

Issue : 
There seems to be an extra padding in the menu on both expanded and collapsed state. See screenshots.
Note that this is not happening when "Notifications are on"

![Screenshot_20200630-091035](https://user-images.githubusercontent.com/47008295/86154636-31c58b00-bab8-11ea-82bf-6c1c21d28e51.png)
![Screenshot_20200630-091042](https://user-images.githubusercontent.com/47008295/86154650-35f1a880-bab8-11ea-9063-6576033a6010.png)

**Comment by srepussard** [comment]
I'm re-opening this one.

Tested on Pixel 3a, Android 10, v25 : **Failed**
- the margin from the expanded menu has been fixed but not from the collapsed menu

![Screenshot_20200707-143505](https://user-images.githubusercontent.com/47008295/86846198-6ceb2f80-c05f-11ea-9ab4-94ec8547f7bb.png)
![Screenshot_20200707-143510](https://user-images.githubusercontent.com/47008295/86846201-6e1c5c80-c05f-11ea-980f-4e45e9faee83.png)

**Comment by JuliannaR** [comment]
@amazingphilippe can you review this?

**Comment by amazingphilippe** [comment]
I cannot replicate on Pixel 2 device+emulator running android 10
I _can_ replicate on Pixel 3a emulator

Seems device specific and we should test more devices to gather more information

I can take a look

**Comment by srepussard** [comment]
Tested on Pixel 3a, Android 10, V46 : **Passed**
- This has been fixed

![Screenshot (Jul  14, 2020 07_43_26)](https://user-images.githubusercontent.com/47008295/87439747-fc379c00-c5a5-11ea-9c76-a1bfa6b7bbdb.png)
