### ISSUE TITLE
Debug menu option to change "monitoring" to "exposed" is very flaky

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/covid-shield-mobile#34]
<img width="561" alt="Screen Shot 2020-06-18 at 12 35 51 AM" src="https://user-images.githubusercontent.com/5498428/84986389-b947ed00-b0fb-11ea-9887-ac65ddbfa0e2.png">

Clicking the menu option to change "monitoring" to "exposed" works about half the time on a real iphone, and never on the ios simulator. Maybe some kind of async issue? Not sure. The relevant code is here: https://github.com/cds-snc/covid-shield-mobile/blob/master/src/testMode/TestMode.tsx#L42

I'm not sure how to fix this and I think this will be crucial for demo'ing - @timarney mind taking a look?

Note that you only see this option with `Mock server: enabled`.

**Comment by timarney** [comment]
https://github.com/cds-snc/covid-shield-mobile/issues/79#issuecomment-647097217

**Comment by timarney** [comment]
Will revisit
