### ISSUE TITLE
Loading errors and warnings: Android 6

### ISSUE THREAD

**Issue by jpeersoxd** [cds-snc/covid-shield-mobile#351]
Environment: Nexus 6/Android 6 (Browserstack)

When the app loads for the first, there are a number of errors and warnings showing up in the Browserstack logs. These may or not be problematic, but they are captured here for informational purposes.

07-01 15:08:20.942 E/SoLoader(14158): couldn't find DSO to load: libjsc.so
07-01 15:08:20.942 W/System.err(14158): java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjsc.so
07-01 15:08:20.942 W/System.err(14158): 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
07-01 15:08:20.942 W/System.err(14158): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
07-01 15:08:20.942 W/System.err(14158): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:587)
07-01 15:08:20.942 W/System.err(14158): 	at com.facebook.soloader.DirectorySoSource.loadDependencies(DirectorySoSource.java:111)
07-01 15:08:20.942 W/System.err(14158): 	at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:71)
07-01 15:08:20.942 W/System.err(14158): 	at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
07-01 15:08:20.942 W/System.err(14158): 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
07-01 15:08:20.942 W/System.err(14158): 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
07-01 15:08:20.943 W/System.err(14158): 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
07-01 15:08:20.943 W/System.err(14158): 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
07-01 15:08:20.943 W/System.err(14158): 	at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:297)
07-01 15:08:20.943 W/System.err(14158): 	at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:271)
07-01 15:08:20.943 W/System.err(14158): 	at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:87)
07-01 15:08:20.943 W/System.err(14158): 	at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:39)
07-01 15:08:20.943 W/System.err(14158): 	at app.covidshield.MainApplication.onCreate(MainApplication.java:75)
07-01 15:08:20.943 W/System.err(14158): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
07-01 15:08:20.943 W/System.err(14158): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
07-01 15:08:20.943 W/System.err(14158): 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
07-01 15:08:20.943 W/System.err(14158): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
07-01 15:08:20.943 W/System.err(14158): 	at android.os.Handler.dispatchMessage(Handler.java:102)
07-01 15:08:20.943 W/System.err(14158): 	at android.os.Looper.loop(Looper.java:148)
07-01 15:08:20.943 W/System.err(14158): 	at android.app.ActivityThread.main(ActivityThread.java:5417)
07-01 15:08:20.943 W/System.err(14158): 	at java.lang.reflect.Method.invoke(Native Method)
07-01 15:08:20.943 W/System.err(14158): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
07-01 15:08:20.943 W/System.err(14158): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by timarney** [comment]
Can someone test this with the latest (ideally on the play store version)

**Comment by jpeersoxd** [comment]
This now starts up on Android 6.
