### ISSUE TITLE
Loading errors and warnings: Android 8.1

### ISSUE THREAD

**Issue by jpeersoxd** [cds-snc/covid-shield-mobile#353]
Environment: Android 8.1/Note 9 (Browserstack)

The following errors/warnings appeared on initial load:
Starting app on Galaxy Note 9
07-01 17:03:08.773 E/Zygote  ( 6207): isWhitelistProcess - Process is Whitelisted
07-01 17:03:08.773 E/libpersona( 6207): scanKnoxPersonas
07-01 17:03:08.773 E/libpersona( 6207): scanKnoxPersonas
07-01 17:03:08.773 E/libpersona( 6207): Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
07-01 17:03:08.775 W/SELinux ( 6207): SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SM-N960F_8.1.0_0004, [-1 -1 -1 -1 0 1]
07-01 17:03:08.775 I/SELinux ( 6207): SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=ca.gc.hcsc.canada.stopcovid

**Comment by timarney** [comment]
Can someone test this with the latest?

**Comment by jpeersoxd** [comment]
Installed the latest from the play store, and it starts up. Great!
