### ISSUE TITLE
French version of Saskatchewan "Find out if you need to be tested" goes to EN site

### ISSUE THREAD

**Issue by jpeersoxd** [cds-snc/covid-shield-mobile#388]
v14, tested on iPhone XS

In the French language version of the app, with location set to Saskatchewan, "Découvrez si vous devriez vous faire tester" sends the user to the English language version of the Saskatchewan government health site. It should go to the French version.

Note that Alberta and BC don't seem to have French versions on their government health sites.

**Comment by JuliannaR** [comment]
@katewilhelm can you verify the link that belongs here?

**Comment by katewilhelm** [comment]
Good catch. That is the link for the NWT self-assessment, but it's probably better to link people here so they get the NWT context and assurance:
**EN** https://www.gov.nt.ca/covid-19/en/services/nwt-online-covid-19-self-assessment-tool
**FR** https://www.gov.nt.ca/covid-19/fr/services/outil-d%E2%80%99auto-%C3%A9valuation-en-ligne-pour-la-covid-19-aux-tno

**Comment by smcmurtry** [comment]
@katewilhelm I think you meant to comment that on #389?

**Comment by katewilhelm** [comment]
oops I did! Sorry!

**Comment by katewilhelm** [comment]
Saskatchewan French should go to English, but the French button needs to say "(lien en anglais seulement)"

Although SK has French content, it's translated automatically and often out of sync with English.

**Comment by smcmurtry** [comment]
This is expected behaviour. As @katewilhelm mentioned we are linking to the english guidance here on purpose, and the french button indicates this with the text:
> (lien en anglais seulement)

<img width="352" alt="Screen Shot 2020-07-04 at 10 38 17 PM" src="https://user-images.githubusercontent.com/5498428/86525638-1c998500-be47-11ea-9cfe-4963db38525c.png">
