### ISSUE TITLE
Northwest Territories: "Find out if you need to be tested" goes to Survey Monkey

### ISSUE THREAD

**Issue by jpeersoxd** [cds-snc/covid-shield-mobile#389]
v14, tested on iPhone XS

Change the region to NWT. In both the French and English versions, if the user clicks "Find out if you need to be tested", they are directed to a Survey Monkey page.

**Comment by JuliannaR** [comment]
@katewilhelm can you verify the link that belongs here?

**Comment by katewilhelm** [comment]
Good catch. That is the link for the NWT self-assessment, but it's probably better to link people here so they get the NWT context and assurance:
EN https://www.gov.nt.ca/covid-19/en/services/nwt-online-covid-19-self-assessment-tool
FR https://www.gov.nt.ca/covid-19/fr/services/outil-d%E2%80%99auto-%C3%A9valuation-en-ligne-pour-la-covid-19-aux-tno
