### ISSUE TITLE
Unable to give app permissions. 

### ISSUE THREAD

**Issue by sidbmw** [cds-snc/covid-shield-mobile#393]
No permission request prompt either. 

OnePlus 7
Android 10

![Screenshot_20200703-150321](https://user-images.githubusercontent.com/16989022/86493148-6480b500-bd3e-11ea-8680-635fcf089ef5.jpg)
![Screenshot_20200703-150324](https://user-images.githubusercontent.com/16989022/86493152-68143c00-bd3e-11ea-9286-f570a0bc3294.jpg)

**Comment by sidbmw** [comment]
Reopening app fixed it?!

![Screenshot_20200703-150806](https://user-images.githubusercontent.com/16989022/86493297-086a6080-bd3f-11ea-8efd-a62ce6f154d4.jpg)

**Comment by sidbmw** [comment]
Bluetooth off:
![Screenshot_20200703-150806](https://user-images.githubusercontent.com/16989022/86493450-9e9e8680-bd3f-11ea-999a-b71e02313b72.jpg)

Bluetooth on:
![Screenshot_20200703-151202](https://user-images.githubusercontent.com/16989022/86493453-9f371d00-bd3f-11ea-8b5d-df65f7055b3c.jpg)
![Screenshot_20200703-151059](https://user-images.githubusercontent.com/16989022/86493454-9f371d00-bd3f-11ea-8fc3-528ef3ae4d69.jpg)

**Comment by jeberhardt** [comment]
I'm having the same issue on a Google Pixel 1, Android 10. 

If I install the version from the Play Store, I get the prompt to turn on permissions. If I build the app on my machine and install it, I don't get the prompt, and permissions are off.

**Comment by timarney** [comment]
@dsamojlenko - thinking this has something to do with the whitelisted account (maybe).

**Comment by timarney** [comment]
@JuliannaR can we try to start tagging as `Play store` vs `apk`

Ideally all testing is being done via the Play store.  Looking to avoid it works when it's installed this way but not that way issues.

**Comment by JuliannaR** [comment]
@timarney attempting to do this now.

**Comment by timarney** [comment]
@JuliannaR this should be re-tested if it hasn't been already.

**Comment by JuliannaR** [comment]
@sidbmw is this still an issue?

**Comment by sidbmw** [comment]
> @sidbmw is this still an issue?

Do you have an apk I can test?

**Comment by timarney** [comment]
Please see this - 

https://github.com/cds-snc/covid-shield-mobile/issues/607#issuecomment-657108583

There's a version # in the Test menu now.

**Comment by sidbmw** [comment]
![Screenshot_20200712-105147.jpg](https://user-images.githubusercontent.com/16989022/87249668-5a417380-c42e-11ea-8236-270d98e8c883.jpg)![Screenshot_20200712-105142.jpg](https://user-images.githubusercontent.com/16989022/87249670-5b72a080-c42e-11ea-9e76-43dbfe8ee634.jpg)

**Comment by timarney** [comment]
Closing this - this can be expected outside of our test tracks.
