### ISSUE TITLE
Notifications should probably have a 'do-not-repeat' mode to avoid pestering people.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-mobile#408]
@emilykuret flagged that after getting into diagnosed state, she received several push notifications in a row.

I'm assuming that this loop is the issue, given the lack of a 'didNotifyToday' flag.

https://github.com/cds-snc/covid-shield-mobile/blob/fdc4eb59eeb7f6f912b38befdeedb253177bacc5/src/services/ExposureNotificationService/ExposureNotificationService.ts#L141

**Comment by emilykuret** [comment]
On Android, the phone did not stack the notifications, but every few mins the time on the notification reset and the phone lit up. 

@jroo submitted a screenshot through TestFlight for how Apple handled it. 
![image](https://user-images.githubusercontent.com/55107923/86517413-bd138900-bdf6-11ea-99f6-50d0e252bd1b.png)

**Comment by timarney** [comment]
Fixed here 
https://github.com/cds-snc/covid-shield-mobile/pull/482
