### ISSUE TITLE
BVC-83 :: Please review usage of USE_FINGERPRINT((deprecated in API 28)) and USE_BIOMETRIC permissions.

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-mobile#409]
=-=-=-
Please review usage of USE_FINGERPRINT and USE_BIOMETRIC permissions.

The USE_FINGERPRINT permission was deprecated in Android 9, so its API calls should be checking as per https://developer.android.com/reference/android/hardware/fingerprint/FingerprintManager. Also, the USE_BIOMETRIC should be added for newer Android devices.
-=-=-=

**Comment by henrytao-me** [comment]
`USE_FINGERPRINT` is not being used for this app. Below is the list of all permissions in the release build. We removed `USE_FINGERPRINT` here https://github.com/cds-snc/covid-shield-mobile/blob/master/android/app/src/release/AndroidManifest.xml#L7

```
    <uses-feature android:name="android.hardware.bluetooth_le" android:required="true"/>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.BLUETOOTH"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.GET_TASKS"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
```

Close as non-issue. Please reopen if needed.
