### ISSUE TITLE
BVC-88 :: Invalid data received from the server fails silently in exposure matching capability of the app

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-mobile#410]
The mobile app can be rendered useless if it receives an invalid value for one of the parameters within the exposure configuration data, which is received from the server after initial app setup. The app does not validate the data received from the server, but the invalid value is rejected later with a silent failure just before an attempt is made to check if the user has been exposed to an infected person.

The app retrieves the exposure configuration from the server via the HTTP GET exposure-configuration request, but does not perform any data validation on the retrieved data.  Later on, the data is used to build the ExposureConfiguration object which is a mandatory parameter of the provideDiagnosisKeys method. The provideDiagnosisKeys is part of the Exposure Notification framework that checks to see if the user was exposed to an infected person. An attempt to update an ExposureConfiguration object with an invalid value (e.g. attenuationWeight = 150) will fail with an IllegalArgument exception. The application does not handle the error nor notify the user nor log the issue. This scenario results in a silent failure that occurs every time an attempt is made to check if the user has been exposed to an infected person essentially disabling the most important feature of the application, thereby rendering it useless as it is unable to recover from this problem.

To reproduce this problem, update the ON.json, that is returned by server, with an invalid value for attenuationWeight (use a value > 100), then install and launch the app to go through the setup process.

Refer to the first line in ExposureNotificationModule:detectExposure() where the failure occurs. Note, an exception is thrown at this point so the call to provideDiagnosiskeys (a few lines below) is never executed. Also, the file with the diagnosis keys(stored in keys.zip) that are meant to be stored temporarily are never deleted.

The app should be robust enough to deal with invalid values that can occur as a result of user configuration errors or a man-in-the-middle attack.

Recommended fix:  

* define valid default values for all parameters that are part of the exposure configuration data structure
* validate all parameters extracted from the JSON file and replace invalid values with default ones.
* Handle all errors as part of the ExposureNotification interface
* ensure keys.zip files don't accumulate

=-=-=-=-

John's note: Apologies, this is like 2-3 tickets, feel free to split apart as needed based on a triage of the potential fix.

**Comment by jeberhardt** [comment]
I have made a PR that addresses a part of this ticket. If the configuration is unable to be downloaded or is non-parseable JSON, then the app will use either a configuration that is included with the app, or will use the previously saved (from download) configuration.

**Comment by jeberhardt** [comment]
The next part of this is to verify that the downloaded configuration is indeed parseable as an ExposureConfiguration object and that the values within it are valid.

**Comment by timarney** [comment]
First part is merged https://github.com/cds-snc/covid-shield-mobile/pull/463

**Comment by jeberhardt** [comment]
The changes made do a significant amount to ensure a configuration was downloaded. 

It throws any network errors, and it throws an error if the downloaded data is not parseable JSON.

The next steps will be to validate:
- that the JSON is a proper configuration,
- and that the values within the configuration are valid.

I believe we should close this ticket and create another one with just those 2 tasks.

**Comment by timarney** [comment]
Discussed the above with @jeberhardt 

The JSON config is served by us and needs Github review on our side if anyone is submitting a new config.

@obrien-j let's pick this up in another ticket as need be.
