### ISSUE TITLE
Android - Increase back button size / touch target - How it works

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-shield-mobile#413]
<img width="313" alt="Screen Shot 2020-07-04 at 11 11 54 AM" src="https://user-images.githubusercontent.com/62242/86515498-3a370200-bde7-11ea-8b27-8967f7510281.png">

**Comment by JuliannaR** [comment]
@timarney @nickmly please see https://github.com/cds-snc/covid-shield-mobile/issues/272#issuecomment-653777080 re arrow vs. back/close used in IOS.
