### ISSUE TITLE
 MOB-H-2: Exposure Code Susceptable to Brute Force Attack

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-mobile#433]
**Analysis of the Issue**
Without limit on how much code, a malicious user can potentially automate a loop through all 8- digit codes to "discover" currently valid codes, and potentially also as some kind of denial of service.

**Recommendation**
Since the code is only for users who are positively diagnosed, there should be very few (3-5) attempts allowed before this backs off very aggressively.

**Comment by obrien-j** [comment]
Given the existing rate limiting measures we have in place within the server and infrastructure level, this does not concern me. 

It may be relevant though to provide a bit of feedback to the users to ensure they don't accidently get themselves blocked for an hour, when trying to input a code. 

We have committed to BBRY to provide a response, with planned remediation, or not, for all issues they've submitted to us.

**Comment by JuliannaR** [comment]
I'm mindful that we need to enable users to get this wrong a few times because its easy to input the numbers wrong. I'd suggest if we were going to limit this 5 attempts would be a good place to land. Are we enabling copy and paste of codes?

**Comment by obrien-j** [comment]
I'm going to close this as 'wont fix', but @JuliannaR, if you don't mind, it may be worth opening a ticket that perhaps has a similar detection limit, and provides a more robust error message to the individual as to what they can do if they need help.
