### ISSUE TITLE
 MOB-H-3: iOS Key Material Stored in Insecure Fashion

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-mobile#434]
**Analysis of the Attack**
The iOS mobile application stores the applications private key unencrypted within the applications container. This key is used as part of the communications exchange between the application and server when submitting the Exposure Notification API data.
An adversary would have to compromise the device to retrieve the key material, but they would then be readily available with no additional compensating controls.

**Recommendation**

The iOS application should leverage either:
• Secure Enclave stored keys
• iOS keychain
The Secure Enclave affords the highest level of security that is currently available within iOS. This mechanism generates keys directly inside the Secure Enclave and prevents them from being exposed within memory. The algorithms supported are restricted. See https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/stor ing_keys_in_the_secure_enclave for official guidance.
iOS allows user data to be stored in an encrypted database called a keychain. The keychain is automatically unlocked when the user unlocks the device and then locked when the device is locked. An application can access only its own keychain items, or those shared with a group to which the app belongs. The affected iOS application should consider using the keychain for storing its key material. See https://developer.apple.com/documentation/security/keychain_services for official documentation.

**Comment by obrien-j** [comment]
Noting that the enclave may not align with the existing methods we're using currently, so we will have to take this under advisement. Similar issues related to the selection of crypto libraries was raised by CCCS as well. Will link tickets once I get them triaged.

**Comment by jeberhardt** [comment]
We are using the `react-native-sensitive-info` package to store the keys generated by the `tweetnacl`.
https://github.com/cds-snc/covid-shield-mobile/blob/afb73c590737ca00fee5bea65b990a842bb783ed/src/services/ExposureNotificationService/ExposureNotificationService.ts#L170

The `react-native-sensitive-info` does use the iOS keychain to store the data. It uses the **SecItemAdd** method to store the keys.
https://github.com/mCodex/react-native-sensitive-info/blob/df602becbdb466b80235f5e4ea9852a45dbb1a41/ios/RNSensitiveInfo/RNSensitiveInfo.m#L147

**Comment by obrien-j** [comment]
Marking as closed. Thanks.
