### ISSUE TITLE
MOB-H-6: Insufficient Encryption in Transit

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-mobile#437]
**Vulnerability Summary**
The application should enforce HTTPS using TLS 1.2, strong ciphers, and SSL certificates. The code present in the mobile application does not appear to enforce HTTPS communication. This was identified by the absence of the expected code.

**Analysis of the Issue**
Conduct a TLS vulnerability scan of the following endpoints or verify the TLS configuration on the server:

**Recommendation**
Encrypting data in transit should be considered mandatory if the application is sending sensitive data over the network, especially given the nature of this application. Without encryption the data sent over the network can be exposed at any point between the client and the server. This can lead to data leakage and provide a view into the application and/or server operations.

Implement on Android, OkHttp’s ConnectionSpec for MODERN_TLS or RESTRICTED_TLS which is a secure configuration that connects the app to modern TLS servers.
OkHttp trusts the certificate authorities of the host platform by default. The platform certificate authorities can be modified on a rooted Android device and will affect the application. Implement OkHttp’s Certificate Pinning or Custom Trusted Certificates in Android to avoid this and limit trust to smaller subset of certificates.
‘CertificatePinner’ may be used to restrict which certificates and certificate authorities are trusted, however, it will make updating the TLS certificates difficult and should be carefully considered. Alternatively, it is possible to replace the host platform’s default certificate authorities with a custom list. Reference the OkHttp documentation for implementation guidance: https://square.github.io/okhttp/https/
Additionally, for both mobile applications:
• Enable support for secure protocols, TLS 1.2, and TLS 1.3.
• Enable support for more secure ciphers suites and give them priority over the currently
supported ciphers in the mobile applications on and the servers:
o AEAD (Authenticated Encryption with Associated Data) cipher suites –
CHACHA20_POLY1305, GCM, and CCM
o PFS (Perfect Forward Secrecy) ciphers – ECDHE_RSA, ECDHE_ECDSA,
DHE_RSA, DHE_DSS, CECPQ1, and all TLS 1.3 ciphers
Note: In order to support the recommended cipher suites, the Android API level must be 29+ (the current target is 28). By supporting the aforementioned ciphers, the most modern devices can take advantage of enhanced levels of security. The servers must also support these ciphers.
Reference:
• https://developer.apple.com/documentation/network (iOS)
o https://developer.apple.com/documentation/network/security_options
• https://developer.android.com/reference/javax/net/ssl/SSLSocket (Android)

**Comment by obrien-j** [comment]
cc: @maxneuvians just flagging this one as it appears to bleed across to the server provided protocols. I'll triage the mobile side later, but my understanding is that we do not provide any http endpoints, and we are in fact providing an HTTPS-ITPIN compliant set of protocols and ciphers. If you could confirm, that'd be helpful. 

Note, there's a buried recommendation for certpinning that I'll pull out of this one. For now, focus on the okhttps portions of the recommendations (mobile team).

**Comment by obrien-j** [comment]
I'm going to mark this one as low priority currently, as we enforce strong TLS/PFS on the server side. Y'all are welcome to investigate equivalent protections client-side as you see fit, but I'm not overly concerned as is.

**Comment by obrien-j** [comment]
Marking as closed, as we've confirmed TLS cipher suites in place on the server side via Cloudfront and ALB tls/ssl directives.

**Comment by H4x0rcr4x** [comment]
Ackknowledged.
