### ISSUE TITLE
MOB-M-6: iOS memory leak in CovidShield.m

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-mobile#442]
dupe of #412 

**Analysis of the Issue**
Review of the function shows the buffer was never freed up and exploring suggestion on replacing malloc with 'NSMutableData'

In function RCT_REMAP_METHOD(getRandomBytes, buff is malloc'd but never freed.

**Recommendation**
Suggestion on new code could look like this:
NSMutableData *buff = [NSMutableData dataWithLength:size];
int status = SecRandomCopyBytes(kSecRandomDefault, size, buff.mutableBytes); if (status == 0) {
NSString *base64encoded = [buff base64EncodedStringWithOptions:0];
resolve(base64encoded); }

**Comment by jeberhardt** [comment]
What's wrong with the solution in this PR?
https://github.com/cds-snc/covid-shield-mobile/pull/430

**Comment by obrien-j** [comment]
Bug came in before the PR. 

dupe of #412
