### ISSUE TITLE
Reduce the font size

### ISSUE THREAD

**Issue by katewilhelm** [cds-snc/covid-shield-mobile#449]
Body text should come down from its current 18 pt to 16 pt. 

Heading text should also shrink by the same proportion. I'm not sure what the heading text sizes are in app, but they should end up being somewhere between 20 and 24 pt.

**Comment by JuliannaR** [comment]
@smcmurtry could you try to find time to get this one in, I think the font size might mean I need to relook through the whole app.

**Comment by timarney** [comment]
https://github.com/cds-snc/covid-shield-mobile/blob/master/src/shared/theme/default.ts#L108

**Comment by timarney** [comment]
Heading Text
https://github.com/cds-snc/covid-shield-mobile/blob/master/src/shared/theme/default.ts#L119

**Comment by nickmly** [comment]
@katewilhelm Does this also include button text? Buttons are currently at 18px as well.
