### ISSUE TITLE
Turn off notification issue with EN notifications - Android

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-shield-mobile#459]
If a user declines to turn on EN notifications in app on Android with a fresh install they may get a screen that disables the ability to turn notifications back on. 
@smcmurtry is going to diverge from how IOS handles this to start the service when the app opens. Steve, If you have additional notes or need to clarify this issue please add to it. 

![Screenshot_20200706-123425](https://user-images.githubusercontent.com/35537308/86618128-5f15ab80-bf86-11ea-97fc-f1269f7d233f.png)

**Comment by timarney** [comment]
Merged.
