### ISSUE TITLE
Add link to thank you screen for ON manual contact tracing form

### ISSUE THREAD

**Issue by katewilhelm** [cds-snc/covid-shield-mobile#470]
After a person in Ontario uploads their random codes, we need to update the thank you screen to include a link to the Ontario test results site. French isn't ready yet, but I'm creating the issue now so that the dev work can start. 

People in Ontario will see a tip on the thank you screen. People outside Ontario or who haven't selected their province will not see a tip.

EN link https://covid19results.ehealthontario.ca:4443/login
FR https://covid19results.ehealthontario.ca:4443/login

ON
<img width="172" alt="Screen Shot 2020-07-06 at 5 44 31 PM" src="https://user-images.githubusercontent.com/57191279/86677362-86da3300-bfc9-11ea-8a17-8bf84bb854ec.png">

Not ON 
<img width="167" alt="Screen Shot 2020-07-06 at 8 46 34 PM" src="https://user-images.githubusercontent.com/57191279/86677668-d0c31900-bfc9-11ea-9383-98a54e874d50.png">

**Comment by smcmurtry** [comment]
New design:
<img width="205" alt="Screen Shot 2020-07-07 at 3 52 57 PM" src="https://user-images.githubusercontent.com/5498428/86847679-f0aa1980-c069-11ea-8ed7-35cd654a5dfc.png">
