### ISSUE TITLE
Does not support landscape orientation [Global] 

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-shield-mobile#473]
This is a known issue for V1Launch. It will also be addressed in the Accessibility Statement.

Landscape orientation is currently disabled. @amazingphilippe this is something we should start considering sooner rather than later. 

Success Criterion [1.3.4 Orientation (Level AA)](https://www.w3.org/TR/WCAG21/#orientation): Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.

This issue links to an upstream issue here: https://github.com/CovidShield/mobile/issues/11

**Comment by timarney** [comment]
Landscape orientation is back on - it needs work but the device accepts it now.

**Comment by timarney** [comment]
@JuliannaR thinking we should close this - and revisit all the sections in v2 as new issues.

**Comment by JuliannaR** [comment]
@timarney Yes, I'll break out new issues for V2 to address landscape orientation.
