### ISSUE TITLE
Splash screen to stay up for 4s

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-shield-mobile#474]
Splash screen to stay up for 4s - technical concerns with doing this right now.

**Comment by henrytao-me** [comment]
I suggest to split splash screen to smaller pieces and use svg to speed it up.

**Comment by nickmly** [comment]
Flagging this: https://github.com/cds-snc/covid-shield-mobile/issues/525#issuecomment-655715166

**Comment by JuliannaR** [comment]
We are closing for this issue: https://github.com/cds-snc/covid-shield-mobile/issues/653
