### ISSUE TITLE
New rectangular illustrations to be added in place of circle ones

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-shield-mobile#476]
We have optimized the illustrations for the app. @amazingphilippe has the updates for this in figma. 
Replacement illustrations exist for **onboarding flow** and **how it works** sections.

**Comment by timarney** [comment]
@jelen-HC note there's an update coming for the onboarding - @henrytao-me will be making a PR this afternoon.

Please flag back to the team if you need anything to complete this.

**Comment by jelen-HC** [comment]
@timarney Should I just leave this for Phil as it seems to be being handled in issue #490 with the updates there?

**Comment by timarney** [comment]
Yes - let's let @amazingphilippe drop them in.
