### ISSUE TITLE
Missing bold text - to match figma

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-shield-mobile#480]
Bold:

Nobody will get any information about you
Personne ne recevra d’informations sur vous

**Bold in Figma not yet applied in the app**
Not tell you in the moment / ne vous dira pas sur-le-champ - screen removed.
Will not tell you about outbreaks - screen removed
Does not use GPS / n’utilise pas le GPS - done
No way of knowing / n’a aucun moyen - done

**Comment by timarney** [comment]
@JuliannaR 

Please confirm after the next build if we're missing any other spots.
