### ISSUE TITLE
"Notifications are off" warning not updating after changing permissions in settings

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/covid-shield-mobile#489]
iOS and Android

Steps to reproduce:
1. install app and answer yes to the "enable push notifications" popup
2. observe that the app does not display the "Notifications are off" warning
1. turn push notifications off in settings ("block all" on android)
2. go back to app
3. observe that the app does not display the "Notifications are off" warning
4. close the app from the task manager
5. re-open the app
5. observe the "Notifications are off" warning is now displayed

**Comment by timarney** [comment]
@henrytao-me this is that other issue I was describing this morning.

**Comment by henrytao-me** [comment]
Close as done
