### ISSUE TITLE
Design changes for release notes (carousel, step 1/6, fade footer, accessibility, icons, illustrations, feedback

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-shield-mobile#490]
**Updates from our chats this morning:**

- We're reverting back to the carousel for the on-boarding screens (@smcmurtry will implement once the design is settled let us know)
- Adding step 1/6 as content on the page (Phil & I have worked out a simple design for this to appear above the titles)
- Adding a "fade" to the footer, to showcase the need to scroll for more content (devs to figure out best way to do this)
- Henry is continuing to work on accessibility solutions for the carousel
- Updating the icon on the upload codes screens to be the "reminder" symbol (I already updated in Figma, Phil will be adding to code)
- Updating the icon on the thank-you screens to be the sign-language symbol for "thank you with love" (I already updated in Figma, Phil will be adding to code)
- Updating the stop sign behind the exposed screen, so it's not crooked (Phil will be making this change)
- Updating all the illustrations in the onboarding and how it works flows to be rectangular (Ioana added to Figma, Phil will be doing this directly in the code)
- We just met with Ontario to talk about content feedback after our MinO demo tomorrow, and some things for us to consider in our next version of the shield menu provincial customization.
- PCO is also currently doing POR on our illustrations for the onboarding/how it works screens in English & French, we'll have their feedback tomorrow :slightly_smiling_face:

**Comment by timarney** [comment]
> Updating all the illustrations in the onboarding and how it works flows to be rectangular (Ioana added to Figma, Phil will be doing this directly in the code)

Same?
https://github.com/cds-snc/covid-shield-mobile/issues/476

**Comment by JuliannaR** [comment]
> > Updating all the illustrations in the onboarding and how it works flows to be rectangular (Ioana added to Figma, Phil will be doing this directly in the code)
> 
> Same?
> #476

Yessum. This is the request you made to add this for release notes purposes.

**Comment by timarney** [comment]
Just pulling out dev tasks here

> Adding a "fade" to the footer, to showcase the need to scroll for more content (devs to figure out best way to do this)

>Henry is continuing to work on accessibility solutions for the carousel

Looks like @amazingphilippe has self tagged on the rest

**Comment by timarney** [comment]
@Stephen-PM can you add an example image here for  -> "Adding a "fade" to the footer"

**Comment by henrytao-me** [comment]
The accessibility in carousel is fixed in How does it work screen. I will bring it to onboarding tomorrow morning.

**Comment by timarney** [comment]
@henrytao-me

>  I will bring it to onboarding tomorrow morning

@smcmurtry is going to do that tonight

**Comment by henrytao-me** [comment]
I see. 🆗

**Comment by amazingphilippe** [comment]
> Updating the icon on the thank-you screens to be the sign-language symbol for "thank you with love" (I already updated in Figma, Phil will be adding to code)

Do we have such a page?

**Comment by Stephen-PM** [comment]
Here is an example of using a fade effect to give affordable that the content continues below the fold. I am not sure if we want it to fade above the footer or within the footer. 
![E35987FC-D12D-4135-BBF1-F0AC0C523F85](https://user-images.githubusercontent.com/63243608/86877278-81a5e280-c0b4-11ea-8db6-208834f76650.png)

**Comment by timarney** [comment]
Going to close - this.

Talked to Eman - remaining item is "the fade" will open a new issue for that.
