### ISSUE TITLE
Missing iOS LaunchScreen images.

### ISSUE THREAD

**Issue by jeberhardt** [cds-snc/covid-shield-mobile#497]
The 1x and 2x LaunchScreen images for iOS are missing.
<img width="888" alt="Screen Shot 2020-07-07 at 12 56 14 PM" src="https://user-images.githubusercontent.com/77435/86816586-fd227800-c051-11ea-943a-fb8c3d731f4e.png">

**Comment by timarney** [comment]
@amazingphilippe ☝️
