### ISSUE TITLE
List items are not read as list on "Get an 8-digit number" screen with VoiceOver

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-shield-mobile#506]
List items are not read as list with VoiceOver.

The selected section in the screenshot is all read as one chunk together as normal text.

iOS 13.5.1 on iPhone 7

![image](https://user-images.githubusercontent.com/14280062/86839709-c5c2c400-c06f-11ea-9ff0-3c7833daeff0.png)

**Comment by JuliannaR** [comment]
Closing this to combine all list issues in previously reported issue.
https://github.com/cds-snc/covid-shield-mobile/issues/268

**Comment by sarasuri** [comment]
Samsung Galaxy J3 Prime
Android version 7.0

Talkback doesn't identify them as a list. It reads each item at a time as normal text.
