### ISSUE TITLE
"Share" random codes only results in "You did not give permission"

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#510]
Environment : 
Pixel 3a, Android 10, v25 from Play Store

Scenario : 
- Navigate to "Enter your 8-digit number" screen
- Enter your code and submit
- Click on "Agree" at the "Now you can upload your codes" screen
- When popup "Share your random IDs" is displayed, click on "Share"

Expected : 
User should be redirected to home screen "Thanks for helping fight..."

Issue : 
Popup is displayed : "Random codes could not be uploaded. You did not give permission."
This popup is displayed whether you clicked on "Share" or "Don't share"

![Screenshot (Jul  7, 2020 14_49_12)](https://user-images.githubusercontent.com/47008295/86847977-0ca9bd00-c062-11ea-9836-dc640b672e2d.png)

**Comment by mtropper** [comment]
@srepussard had you infected the phone already that day and were reinfecting the phone?

**Comment by srepussard** [comment]
I'm pretty sure this was a fresh install of the app

**Comment by timarney** [comment]
Can you confirm what version of the EN Framework your using?

<img width="300" src="https://user-images.githubusercontent.com/62242/87050477-4e567700-c1cc-11ea-8825-622ec877790a.png">

**Comment by nickmly** [comment]
I am getting the same thing with this version:
![Screenshot_20200709-102515_Google Play services](https://user-images.githubusercontent.com/5861415/87053441-f1f55680-c1cf-11ea-8e8d-a6bf2efb1d1a.jpg)

**Comment by JuliannaR** [comment]
@timarney @srepussard I know there were some issues around how many times you could infect a device. Max had some conversations about this and key data. I was not getting a version number at the bottom.

**Comment by timarney** [comment]
@srepussard @nickmly I believe this is corrected now after a server update.

https://github.com/cds-snc/covid-shield-server/pull/158

**Comment by srepussard** [comment]
Tested on Pixel 3a, Android 10, v33 from Play Store : **Passed**
- I confirm that this has been fixed. We are now redirected to "Thanks for helping fight..." screen
