### ISSUE TITLE
Android - Exposure Notifications needs Bluetooth and Location to work

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#521]
We found out that Android seems to have a different behavior than iOS about Location for EN to work. We always assumed Location is not needed and implemented the app around this assumption. We need to investigate this.

Google documentation here refers to turning on your phone's Location setting as the system uses this to scan for Bluetooth signals : https://support.google.com/android/answer/9888358?hl=en

Here are screenshots from the "Turn on EN" popups where it clearly mentions using Location : 

![Screenshot_20200707-200715](https://user-images.githubusercontent.com/47008295/86870918-22cd7280-c08e-11ea-85ca-5e6bca945e15.png)
![Screenshot_20200707-200721](https://user-images.githubusercontent.com/47008295/86870921-23660900-c08e-11ea-8795-6161ee4da4e7.png)

Turning on EN via this popup does turn on the phone's BT and Location. And if both of these are turned off, a push notification shows up on the phone "EN is inactive. To use this feature, turn on Bluetooth and location."

**Comment by JuliannaR** [comment]
@Stephen-PM - is looking into this right now with folks at Google.

**Comment by timarney** [comment]
@Stephen-PM any action to be taken here?

**Comment by jpeersoxd** [comment]
Tested on Pixel 3a. Can confirm this is no longer an issue. @JuliannaR please close.
