### ISSUE TITLE
Android on-boarding screens Step 2 doesn't match iOS on-boarding flow (Android 8)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#523]
onePlus 3, Android v 8
app version - July 7 according to the GooglePlay store
Reinstalled app
Open app
Splash screen is displayed.
Step 1:  together, let's stop the spread of COVID-19 is displayed.
Step 2:
iOS  = totally anonymous
android  = What COVID Alert does not do.

according to Figma flow should be 
![image](https://user-images.githubusercontent.com/65728700/86912593-4541a900-c0eb-11ea-9724-7fd45d7f160f.png)

**Comment by mtropper** [comment]
@JuliannaR the screens match but the latest build for Android hasn't been released yet

**Comment by JuliannaR** [comment]
@mtropper thanks! a new build for android is likely releasing today. @mmiron-HC we switched up the order of these screens in an issue yesterday. You will see the fix as soon as a new android version is released. https://github.com/cds-snc/covid-shield-mobile/issues/451

**Comment by timarney** [comment]
For line of sight we had to do a small patch for testing on iOS last night specifically.

Moving forward we'll be trying to get our release pipeline setup so these patch tests get directed to a few select people vs a larger release.

cc: @dsamojlenko

**Comment by timarney** [comment]
We're now at 1.0 (v20)
