### ISSUE TITLE
Reading order is incorrect on COVID Alert menu with TalkBack on

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-shield-mobile#542]
With TalkBack on, the initial focus is at the COVID Alert menu at the bottom of the screen. It end up creating incorrect reading order. It's read as the 1st item on the page/screen when "Read from top" is selected in Global content menu. On iOS, it's the last item which is correct.

Android 8.1.0 on Samsung Galaxy
Android 10 on OnePlus 7

![image](https://user-images.githubusercontent.com/14280062/86955472-a1292380-c125-11ea-9486-2e0204b3dca6.png)

**Comment by sarasuri** [comment]
Samsung Galaxy J3 Prime
Android version 7.0

The same issue occurs on both COVID Alert is off/COVID Alert is active screens.
![menu](https://user-images.githubusercontent.com/12256067/86965657-e2c1ca80-c135-11ea-8578-d4f1c2578ee2.gif)

**Comment by smcmurtry** [comment]
This is a tricky one - I'm not sure how to fix this. The focus order of elements is determined differently in Android vs. iOS. We can't manually specify the focus order on Android (like with `tabindex` on the web). This would take more investigation into how Android is determining the focus order and what we would do to change that.

**Comment by JuliannaR** [comment]
@qanitah I have combined the focus issues here https://github.com/cds-snc/covid-shield-mobile/issues/563
