### ISSUE TITLE
Focus is at incorrect location/space on COVID Alert menu with TalkBack on 

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-shield-mobile#544]
On Android with TalkBack on, "Close button" focus is lower than at the closing arrow on top for COVID Alert menu.

Android 8.1.0 on Samsung Galaxy
Android 10 on OnePlus 7

![image](https://user-images.githubusercontent.com/14280062/86958689-8efdb400-c12a-11ea-8549-1f8cc5932324.png)

**Comment by sarasuri** [comment]
Samsung Galaxy J3 Prime
Android version 7.0

Same issue as mentioned above.

**Comment by JuliannaR** [comment]
@qanitah and @sarasuri This issue has been grouped with focus related issues for the shield expand and collapse. https://github.com/cds-snc/covid-shield-mobile/issues/new
