### ISSUE TITLE
Content is not read in correct order with Talkback on after Done button

### ISSUE THREAD

**Issue by sarasuri** [cds-snc/covid-shield-mobile#548]
Samsung Galaxy J3 Prime
Android version 7.0

On the on-boarding screen Step 6, after swiping right to each item to "Done" button at the bottom of the screen and if user continues to swipe to the right, Talkback starts reading from "New Brunswick" instead from the top of the screen.

Expected result
Talkback should read from the top of the screen after the "Done" button.

WCAG
https://www.w3.org/WAI/WCAG21/Understanding/focus-order.html

Screenshots
![step6a](https://user-images.githubusercontent.com/12256067/86962997-c754c080-c131-11ea-83a7-f0e3c552f5f5.gif)
![step6b](https://user-images.githubusercontent.com/12256067/86963000-c91e8400-c131-11ea-8069-96eb13151206.gif)

**Comment by JuliannaR** [comment]
@sarasuri I can't reproduce this. Swiping right for me moves back to the header. Could you retest with the lastest update on Android and let me know if it's still an issue.

**Comment by sarasuri** [comment]
@JuliannaR 
Initially the focus is on the "Done" button and swiping right takes user to the top. However, if user swipes through to the Done button again and continue swiping right again from the "Done" button at that point it doesn't move back to the header.

**Comment by JuliannaR** [comment]
@sarasuri similar problem here https://github.com/cds-snc/covid-shield-mobile/issues/548
I've grouped them together.
