### ISSUE TITLE
Focus isn't where it should be on iOS using VO

### ISSUE THREAD

**Issue by paulettefrancis** [cds-snc/covid-shield-mobile#565]
When you get to the Privacy policy page, using VO, the focus is on the heading but should be on "Close" as it is the first item on the page.

Tested using iPhone XR 13.5.1

**Comment by JuliannaR** [comment]
@paulettefrancis we have a combined issue for focus issues. We are starting focus on the first heading of screens pending usability findings.
I've grouped this for follow up here: https://github.com/cds-snc/covid-shield-mobile/issues/563
