### ISSUE TITLE
Link on Get an 8-digit number should go to the French site

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#566]
iOS iPhone XR (iOS language = FR)
following test case #52 
Province = Ontario
COVID19 Exposure/Notifications/Bluetooth = on.
app language = French
version 30

from the menu, selected Obtenir un numéro à 8 chiffres
From the page titled the same Obtenir un numéro à 8 chiffres, clicked the aller sur le site des Résultats du test pour la COVID-19.
Browser is opened to COVID19results.ehealthontario.ca but in English
Expected result: user should be navigated to the french link.

**Comment by its-anirudh** [comment]
@timarney @JuliannaR @mmiron-HC eHealth does not provide a standalone French link. For this exact functionality it requires them to make changes to their site and we cannot do much on our end. However, the button to change language is pretty prominent so I cannot action anything at the minute

![image](https://user-images.githubusercontent.com/65962820/87089392-60540c00-c204-11ea-923e-55bdfc69b22d.png)

**Comment by timarney** [comment]
"Link on Get an 8-digit number should go to the French site"

@its-anirudh  > eHealth does not provide a standalone French link.

☝️ 

@Stephen-PM

**Comment by srepussard** [comment]
Additional note that this issue also happens for the "Test results website" link on the "Thanks for helping fight..."

**Comment by mmiron-HC** [comment]
@JuliannaR @timarney at this point it is in your hands. Let us know what the decision is as we will need to make sure the Test cases reflect this.

**Comment by JuliannaR** [comment]
@mmiron-HC Ontario will not have a direct french link. People will navigate and need to use the french language toggle at the top of the page. 
Closing this one. Thanks!
