### ISSUE TITLE
Screen doesn't move when reading using VO

### ISSUE THREAD

**Issue by paulettefrancis** [cds-snc/covid-shield-mobile#567]
With VO on, if I tap on "Tap for menu" (COVD Alert is off), and swipe, the screen doesn't move when the text "Push notifications...." is read.

Same thing happens on the "COVID Alert is active" page. The screen doesn't move and unable to read the rest of the page. 

Tested using iPhone XR 13.5.1

![Screen](https://user-images.githubusercontent.com/22638158/87047353-65936580-c1c8-11ea-850b-7b3ea4ad6077.jpg)

![Screen2](https://user-images.githubusercontent.com/22638158/87054304-f4a47b80-c1d0-11ea-9e38-244b080c4282.jpg)

![Screen3](https://user-images.githubusercontent.com/22638158/87054317-f8d09900-c1d0-11ea-91a7-68f16b40e2e8.jpg)

**Comment by JuliannaR** [comment]
@paulettefrancis I have added this to a group of known issues across multiple screens in the app to address focus and reading order issues. 
https://github.com/cds-snc/covid-shield-mobile/issues/563
