### ISSUE TITLE
Push notification doesn't work cosistently

### ISSUE THREAD

**Issue by henrytao-me** [cds-snc/covid-shield-mobile#570]
## Potential issue with background tasks on iOS?

Test results Timeline:

2PM eastern July 7 - Emily's friends download the app onto their iPhones
6:45PM July 7 - Emily arrives at their house with "positive diagnosed" state on her Pixel
10PM July 7 - Emily leaves friends house
Night of July 7 - friends charge phone
Morning/Afternoon of July 8 - friends do not open app, do not recieve notification
4:37 pm July 8 - friends open app and see the app go to an exposed state
Exposure log:
![IMG-20200708-WA0006](https://user-images.githubusercontent.com/5498428/87058958-f452b300-c1c5-11ea-842e-76fdbdd63510.jpg)

**Comment by emilykuret** [comment]
Updating experiment details and timelines: 
July 9 - 3:45PM - Friend receives an exposure notification, logs were checked throughout the day, without Jeff opening the app, some logs had matched keys 
July 9 - 5:30PM - Friend clears the logs, deletes the log and then reinstalls the app
July 10 - 12:08AM - Received another exposure notification

**Comment by henrytao-me** [comment]
Close as resolved by https://github.com/cds-snc/covid-shield-mobile/issues/642 and we know iOS implementation is correct. It's recommended for iOS to minimize the app instead of terminating. cc @jeberhardt
