### ISSUE TITLE
useI18n hook causes `backgroundScheduler.registerPeriodicTask` calling twice in ExposureNotificationServiceProvider

### ISSUE THREAD

**Issue by henrytao-me** [cds-snc/covid-shield-mobile#583]
## What?

`useI18n` hook causes `backgroundScheduler.registerPeriodicTask` calling twice in ExposureNotificationServiceProvider. It should be called only once. Being called multiple times wouldn't cause big issues, except it would hit rate limit for `provideDiagnosisKeys` more quickly. 

## Proposal
Look into how I18nManager is constructed and create a better version. 

From below log, look like the first time it is called, it doesn't return full data or something. 

```
[Thu Jul 09 2020 16:16:22.349]  LOG      ccccccc setExposureNotificationService {"defaultCountry": undefined, "defaultCurrency": undefined, "defaultTimezone": undefined, "getCurrencySymbol": [Function anonymous], "loading": true, "locale": "en", "onError": [Function onError], "pseudolocalize": false, "translations": [{"BottomSheet": [Object], "DataUpload": [Object], "Home": [Object], "HowToIsolate": [Object], "Info": [Object], "LanguageSelect": [Object], "Notification": [Object], "Onboarding": [Object], "OverlayClosed": [Object], "OverlayOpen": [Object], "Partners": [Object], "Privacy": [Object], "RegionLanding": [Object], "RegionPicker": [Object], "RegionalGuidance": [Object], "Sharing": [Object], "ThankYou": [Object], "Tutorial": [Object]}]}

[Thu Jul 09 2020 16:16:22.395]  LOG      ccccccc setExposureNotificationService {"defaultCountry": undefined, "defaultCurrency": undefined, "defaultTimezone": undefined, "getCurrencySymbol": [Function anonymous], "loading": false, "locale": "en", "onError": [Function onError], "pseudolocalize": false, "translations": [{"BottomSheet": [Object], "DataUpload": [Object], "Home": [Object], "HowToIsolate": [Object], "Info": [Object], "LanguageSelect": [Object], "Notification": [Object], "Onboarding": [Object], "OverlayClosed": [Object], "OverlayOpen": [Object], "Partners": [Object], "Privacy": [Object], "RegionLanding": [Object], "RegionPicker": [Object], "RegionalGuidance": [Object], "Sharing": [Object], "ThankYou": [Object], "Tutorial": [Object]}, {"BottomSheet": [Object], "DataUpload": [Object], "Home": [Object], "HowToIsolate": [Object], "Info": [Object], "LanguageSelect": [Object], "Notification": [Object], "Onboarding": [Object], "OverlayClosed": [Object], "OverlayOpen": [Object], "Partners": [Object], "Privacy": [Object], "RegionLanding": [Object], "RegionPicker": [Object], "RegionalGuidance": [Object], "Sharing": [Object], "ThankYou": [Object], "Tutorial": [Object]}]}
```

**Comment by obrien-j** [comment]
https://www.coronawarn.app/de/faq/#ENError13 <-- @henrytao-me just flagging this for visibility.

**Comment by timarney** [comment]
Looking at the logs could could we simply check on 

```
loading:
```

I see it's false in the first log and true in the second.

**Comment by mmiron-HC** [comment]
Samsung S10
left the app running in background overnight after exposed to positively diagnosed device. 
re-opened the app after 24hr+ and noticed that the home screen displays No exposure detected. close and re-open the app and now I have Exposure detected message. 
expected behaviour: background refresh should set the proper message on the home screen.

**Comment by henrytao-me** [comment]
@mmiron-HC 

Can I know how long after you first time open the app until you close / re-open again? Android take EN framework takes time to calculate Exposure Summary. For a small set of keys, it takes around 7s after making a request. Our server has over 800 keys, it might take a bit longer.

**Comment by mmiron-HC** [comment]
@henrytao-me i can't be certain, but it would have been a few minutes b/c I went to check the Exposure checks log to see when the last ping was. then I closed/re-opened the app.
