### ISSUE TITLE
Propose a better flow to handle async result from detectExposure on Android

### ISSUE THREAD

**Issue by henrytao-me** [cds-snc/covid-shield-mobile#595]
## What?

Calling `detectExposure` on Android doesn't return result immediately like iOS. Android needs to wait for result from Broadcast Receiver which could take a long time. In some cases, the app is closed before the receiver sends summary back.

**Comment by henrytao-me** [comment]
# Exploration summary:

## Existing flow from [react-native-background-fetch](https://github.com/transistorsoft/react-native-background-fetch) library 

#### On Andorid:
- App is launched the first time. 
- The app calls `BackgroundFetch.configure` and then `BackgroundFetch.scheduleTask`. 
- The lib will schedule background job to run the app according to the configuration. 


#### On iOS:
- App is launched the first time. 
- The app calls `BackgroundFetch.configure` and then `BackgroundFetch.scheduleTask`. 
- The lib will schedule background job to run the app according to the configuration. 
- Based on the docs here https://github.com/transistorsoft/react-native-background-fetch#implementation, it says `Unlike iOS, the Android implementation can continue to operate after application terminate (stopOnTerminate: false) or device reboot (startOnBoot: true).`. This is not true based on what we have been tested. iOS can still run and show notifications after the app is terminated. 
- Unlike Android, there is no need to register for headlessTask `AppRegistry.registerHeadlessTask` https://reactnative.dev/docs/headless-js-android.html. It appears that iOS can run the whole app headless by default as long as iOS background job is run. When the whole app is run headless, it will render HomeScreen, hence calling `ExposureNotificationService.start`, hence updating exposureStatus.

**Comment by eljojo** [comment]
### For Option 2:
Would the timeout not apply if we used WorkManager? From the linked GH issue:
> The only thing WorkManager will do is simplify the code a bit. It won’t change the actual performance. Under-the-hood, WorkManager is using JobScheduler for devices running >= Lollilop; AlarmManager for everything else.

I agree that increasing the timeout is not a good idea, maybe it takes 30s in a good phone in good conditions, but if for decent hardware we're seeing issues, I'd assume minutes for lower-end phones on poor 3G.

### For Option 4
I am not really a react native dev, but I agree that option 4 makes a lot of sense.
Would you be able to split this in say, three milestones?
- option 1 first (with the "you're seeing yesterday's notification" bug)
- option 1 + 3: local notification in native layer.
  - could we pass the translation from the JS layer ahead of time so we don't have to port translation into native?
- option 4: all of the above I guess?

**Comment by henrytao-me** [comment]
@eljojo Thanks for the comments.

- Regarding option 2: that's what I am thinking. It's not an ideal solution. 
- I would like to just go straight to option 4 (included option 1). Combining option 3 isn't a good addition as it introduces more fragment in the code.

**Comment by henrytao-me** [comment]
PR is up https://github.com/cds-snc/covid-shield-mobile/pull/640

**Comment by henrytao-me** [comment]
Close as done. Tested with @timarney Let's see how it perform.
