### ISSUE TITLE
Page is not readable as focus is in the wrong place using VO in iOS

### ISSUE THREAD

**Issue by paulettefrancis** [cds-snc/covid-shield-mobile#604]
When you get to the 'COVID Alert is off' page, after selecting 'Don't Allow' from the Notifications popup window, the focus is at the top on the signal strength.

If I swipe up to read the page, it only reads what's at the very top (time, strength, Testflight, etc.) and doesn't read the page at all.

Tested on iPhone XR 13.5.1

![Focus](https://user-images.githubusercontent.com/22638158/87165741-8fb45880-c298-11ea-998f-34b40cba5cfa.jpg)

**Comment by JuliannaR** [comment]
This is because of the testflight demo menu.
