### ISSUE TITLE
COVID Alert has stopped working - Android 8 (v33)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#607]
One Plus 3 Android 8
App version 33 is installed
COVID 19 Exposure notifications are ON,
Notifications = On
Bluetooth = On
Entered a valid diagnosis code earlier this morning.

Left the app running in the background and left phone.
1hr or so later, returned to phone and had a message: COVID Alert has stopped. see image.
Was able to reproduce it 3x 

![COVIDAlert has stopped](https://user-images.githubusercontent.com/65728700/87166395-82e43480-c299-11ea-9670-ef80665454ee.jpg)

**Comment by JuliannaR** [comment]
On Android 8.1.0 on Samsung Galaxy, just changed one or more things and went back to the app, the app had crashed with message "COVID Alert has stopped". Happened every time for me (3 times just now). Used recents/app switcher to switch between apps.

On Android 10 on OnePlus 7, changed font size and display size and tried to switch back to the app and it crashed. Happens every time I try to change a couple of things and go back and then change again and go back (so have to go to settings a couple of times). Just tried 4 times and got this every time. Used recents/app switcher to switch between apps.

Android 8.1.0 on Samsung Galaxy
Android 10 on OnePlus 7

https://github.com/cds-snc/covid-shield-mobile/issues/612

**Comment by timarney** [comment]
Let's see what happens on 

v43

There's a new option in the menu where you can type in a UUID for debugging.  If you can add a unique ID for that 
value and also check that you have v43 version (you can now see it in the test menu at the bottom) that would be helpful. 

<img width="300" src="https://user-images.githubusercontent.com/62242/87231171-c5357080-c382-11ea-9b0b-e94a8d275fcb.png">

**Comment by timarney** [comment]
If possible it would be very helpful to capture a bug report:

## Capture a bug report from a device

See: https://developer.android.com/studio/debug/bug-report

```
- Be sure you have Developer Options enabled.
- In Developer options, tap Take bug report.
- Select the type of bug report you want and tap Report.
- After a moment you get a notification that the bug report is ready 
- To share the bug report, tap the notification.
```

**Comment by henrytao-me** [comment]
@mmiron-HC 

> Left the app running in the background and left phone. 1hr or so later...

Did you just minimize the app or terminate it completely?

**Comment by henrytao-me** [comment]
Log an issue about crash after changing system font https://github.com/cds-snc/covid-shield-mobile/issues/651

**Comment by henrytao-me** [comment]
@mmiron-HC @JuliannaR Can you please take another look? It should be ready in upcoming build > 46.

**Comment by timarney** [comment]
I'll do another build tonight - so will be ready for another test in the morning.

**Comment by timarney** [comment]
v47 should be available now.

cc: @henrytao-me

**Comment by henrytao-me** [comment]
👍

**Comment by mmiron-HC** [comment]
with version 47, I cannot get the OnePlus 3 to crash whatsover. I've tried other androids as well and can't make it crash - leaving open as other HC testers WCAG were having issues this morning with this.

**Comment by sarasuri** [comment]
Samsung Galaxy J3 Prime
Android version 7.0
App version= 1.0 (49)

App has stopped working.

Installed the latest version
Step 6  - Clicked Cancel on the Turn on notification popup
Choose "Prefer not to say" radio button option for province
Pressed "Done" on the Step 6.
COVID Alert has stopped popup is displayed
Pressed "Send feedback" to send feedback

**Comment by JuliannaR** [comment]
@henrytao-me I've advised the team to send crash reports, will that be helpful to isolating and tracking this down?

**Comment by henrytao-me** [comment]
Thanks @sarasuri and @JuliannaR. I found the bug report. Looking into it now.

https://play.google.com/apps/publish/?account=9219591942344823003#AndroidMetricsErrorsPlace:p=ca.gc.hcsc.canada.stopcovid&appid=4973693627104887436&appVersion&clusterName=apps/ca.gc.hcsc.canada.stopcovid/clusters/12189a7c&detailsAppVersion&detailsSpan=7.

**Comment by henrytao-me** [comment]
I will close this issue as the original issue is fixed. New issue is log here https://github.com/cds-snc/covid-shield-mobile/issues/709. IMO, new issue is optional for v1launch.
