### ISSUE TITLE
Unable to use 2-finger swipe with VO on in iOS

### ISSUE THREAD

**Issue by paulettefrancis** [cds-snc/covid-shield-mobile#609]
On the 'COVID Alert is off' page, after selecting 'Don't Allow' from the Notifications popup window, I'm unable to use the 2-finger swipe up to read the whole page. 

Tested on iPhone XR 13.5.1

![Swipe](https://user-images.githubusercontent.com/22638158/87166982-52e96100-c29a-11ea-899c-18d5e4a31e93.jpg)

**Comment by JuliannaR** [comment]
This is because the test menu is back for tester, we validated that this will not be a problem when the button for demos is removed.
