### ISSUE TITLE
App keeps crashing in Android - "COVID Alert keeps stopping" OR "COVID Alert has stopped" 

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-shield-mobile#612]
On Android 8.1.0 on Samsung Galaxy, just changed one or more things and went back to the app, the app had crashed with  message "COVID Alert has stopped". Happened every time for me (3 times just now). Used recents/app switcher to switch between apps.

On Android 10 on OnePlus 7, changed font size and display size and tried to switch back to the app and it crashed. Happens every time I try to change a couple of things and go back and then change again and go back (so have to go to settings a couple of times). Just tried 4 times and got this every time. Used recents/app switcher to switch between apps.

Android 8.1.0 on Samsung Galaxy
Android 10 on OnePlus 7

![image](https://user-images.githubusercontent.com/14280062/87173332-94cad500-c2a3-11ea-973a-29c8f36fd7af.png)

![image](https://user-images.githubusercontent.com/14280062/87173313-8da3c700-c2a3-11ea-8bc0-9d118da7fff4.png)

**Comment by sarasuri** [comment]
Samsung Galaxy J3 Prime
Android version 7.0

Similar behaviour happened. When try to switch between languages French and English the app has stopped.

**Comment by JuliannaR** [comment]
@qanitah and @sarasuri I am combining this request with @mmiron's. https://github.com/cds-snc/covid-shield-mobile/issues/607
