### ISSUE TITLE
Remove change language option from menu

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-shield-mobile#615]
Please remove the change language option from the menu within the app.

It introduces problems with system level notifications vs. in app locations and now we released in french there are some pieces of the content not reading properly when switched in app but does read when switched at the system level.

**Comment by mtropper** [comment]
@JuliannaR @timarney  Facebook changes language on the OS level as an app preference. I wonder if that is something we could implement for the Covid Alert app as well
![image](https://user-images.githubusercontent.com/52504483/87184727-833ef880-c2b6-11ea-9f2b-fa0b48bd2cc4.png)

**Comment by mtropper** [comment]
@JuliannaR @timarney  The option is actually already there by default in IOS 13 we just need to have the language toggle link to this section 
![image](https://user-images.githubusercontent.com/52504483/87185517-e5e4c400-c2b7-11ea-8a45-ad014f78eb5f.png)

**Comment by mtropper** [comment]
How ever it only works in IOS
