### ISSUE TITLE
Some text wrap with accessibility features on

### ISSUE THREAD

**Issue by sarasuri** [cds-snc/covid-shield-mobile#622]
Scenario to reproduce 

Samsung Galaxy J3 Prime
Android version 7.0

Accessibility features:

Settings - Accessibility - Vision - Screen zoom and Font – Screen zoom - changed to largest
Settings - Accessibility - Vision - Screen zoom and Font –  Font size - changed to Huge

When testing with some accessibility features on, some text wrap to the next line in French.
In addition, check mark used to indicate the selected province is slightly cut off in both English and French for the long names.

Screenshots
![text-resize](https://user-images.githubusercontent.com/12256067/87191461-732d1600-c2c2-11ea-9e56-2458b35133f9.gif)
![text-resize2](https://user-images.githubusercontent.com/12256067/87191464-73c5ac80-c2c2-11ea-9d44-3a92308767f0.gif)
![text-resize3](https://user-images.githubusercontent.com/12256067/87191465-73c5ac80-c2c2-11ea-95d0-4ec7dc03972b.gif)

**Comment by JuliannaR** [comment]
Yes, this is okay. We need to meet 200% font increase or zoom without breaking to keep the design responsive. The app can move to between 500%-800% magnification currently.

![Image from iOS (57)](https://user-images.githubusercontent.com/35537308/87193187-277c6b80-c2c6-11ea-8761-59cf3fc8ab19.png)
![Image from iOS (54)](https://user-images.githubusercontent.com/35537308/87193174-20555d80-c2c6-11ea-8af8-d155bf73fcf8.png)
![Image from iOS (55)](https://user-images.githubusercontent.com/35537308/87193180-23e8e480-c2c6-11ea-9953-cf8c9bde91f5.png)
![Image from iOS (56)](https://user-images.githubusercontent.com/35537308/87193181-25b2a800-c2c6-11ea-98c1-14f98a4878b0.png)
