### ISSUE TITLE
Word "Précédent" wraps in Android 7

### ISSUE THREAD

**Issue by sarasuri** [cds-snc/covid-shield-mobile#652]
Scenario to reproduce

Samsung Galaxy J3 Prime
Android version 7.0
App version: 1.0 (46)
Language = French

After pressing "Suivant" button on the Step 1 and "How COVID Alert works" screens, text "Précédent" on the button wraps.

Expected result
The word shouldn’t wrap.

Screenshots
![step2-fr](https://user-images.githubusercontent.com/12256067/87311158-e1552100-c4ec-11ea-9413-ce1a029d07b5.gif)
![step2a-fr](https://user-images.githubusercontent.com/12256067/87311814-be773c80-c4ed-11ea-85d8-620fd8546f0f.gif)

**Comment by its-anirudh** [comment]
HI @sarasuri  I could not reproduce this issue. I set up a new device with the Specs matching the Samsung J3 prime (5.0 inches,Resolution | 720 x 1280 pixels). The word appears fine:
![image](https://user-images.githubusercontent.com/65962820/87340582-41ac8880-c516-11ea-872c-f250821cc172.png)

**Comment by qanitah** [comment]
I get the same issue for Android 8.1.0 on Samsung Galaxy. Also attaching font size where it starts to wrap in.

![image](https://user-images.githubusercontent.com/14280062/87342366-1ecfa380-c519-11ea-9afc-5e5de72d910a.png)

![image](https://user-images.githubusercontent.com/14280062/87342393-2d1dbf80-c519-11ea-9826-3431f570e714.png)

**Comment by its-anirudh** [comment]
> I get the same issue for Android 8.1.0 on Samsung Galaxy. Also attaching font size where it starts to wrap in.
> 
> ![image](https://user-images.githubusercontent.com/14280062/87342366-1ecfa380-c519-11ea-9afc-5e5de72d910a.png)
> 
> ![image](https://user-images.githubusercontent.com/14280062/87342393-2d1dbf80-c519-11ea-9826-3431f570e714.png)

Is this physical device or emulator ?

**Comment by qanitah** [comment]
Actual device/phone.

**Comment by sarasuri** [comment]
For Android 7 issue, it is actual device/phone as well.

**Comment by its-anirudh** [comment]
@JuliannaR @sarasuri I have a potential fix, however the catch is that Progress circle start off slightly off center but once the navigation starts they set into place.

The screenshots are for the onboarding module, but it will be the same in 'How-to'. Please advise

1.
![image](https://user-images.githubusercontent.com/65962820/87363716-bf38be80-c53f-11ea-8605-386534ac1171.png)

2.
![image](https://user-images.githubusercontent.com/65962820/87363747-d4ade880-c53f-11ea-8b58-81aca70912e0.png)

**Comment by JuliannaR** [comment]
@amazingphilippe can you take a look here, I think we will want to avoid having the dots be off centre.
