### ISSUE TITLE
Share your random codes notification no longer appearing

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-shield-mobile#662]
**Scenario**:
On subsequent days the notification for sharing your codes is no longer appearing in the screen flow.

**Expected Behaviour**
Every time you use the agree button you would receive the notification to share or not.

**Screenshot**
<img width="414" alt="Screen Shot 2020-07-13 at 12 39 35 PM" src="https://user-images.githubusercontent.com/35537308/87330509-ad86f500-c506-11ea-875e-1a92fa169c81.png">

**Devices**
Nexus 6 8.1 Android
iPhone 8, IOS 13.5.1

**Comment by henrytao-me** [comment]
The framework controls consent dialog. It keeps consent for 24h based on what I know. So, it won't ask user again for consent and will reset the next day (UTC timezone).

I would say it is not a bug.

**Comment by JuliannaR** [comment]
Shouldn't it not ask me to reshare my codes for that window in that case? Or it will be out of sync often?

**Comment by henrytao-me** [comment]
I think there are two different concerns: 
- App asks user to upload new keys. 
- Framework asks user for consent. 

They shouldn't be tight together.

**Comment by JuliannaR** [comment]
Thanks, I will close this out.
