### ISSUE TITLE
Focus doesn't go to heading in landscape orientation

### ISSUE THREAD

**Issue by paulettefrancis** [cds-snc/covid-shield-mobile#675]
When in landscape orientation, the focus doesn't go to the top of page, but on a paragraph on the Privacy policy page.

The focus goes to the heading in portrait orientation as it should.

Tested on iPhone XR 13.5.1.

![Focus](https://user-images.githubusercontent.com/22638158/87443576-ad98fa80-c5c3-11ea-9aad-277e3b69c08b.jpg)

**Comment by JuliannaR** [comment]
Combined landscape orientation issues here https://github.com/cds-snc/covid-shield-mobile/issues/701
