### ISSUE TITLE
Update app to use UTC vs device local time

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-shield-mobile#676]
We need to standardize the app to use UTC to ensure consistency.

Ideally any date time functions / calls should be here:

```
 src/shared/date-fns.ts
```

**Comment by timarney** [comment]
@dsamojlenko tagging you to mark as "this is assigned" we'll sync on Slack for this.

**Comment by henrytao-me** [comment]
Note: we should continue looking into UTC VS device timezone to find all race conditions that could mess up user experience.  For example: 
- Missing the last key upload because device timezone reaches 0 day and reset the UI while in UTC timezone, user still has to upload one more time.
