### ISSUE TITLE
Airplane/no data screen does not show when phone is in positive diagnosis

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#678]
Environment : 
Pixel 3a, Android 10, v46 from Play Store
iPhone 8, v46 TestFlight

Scenario : 
- Make sure this phone is in a positive diagnosis state (code entered)
- Open the app
- Turn on airplane mode on your phone (make sure Bluetooth is on)
- Return to app home screen

Expected : 
No data/airplane mode screen should have been displayed "COVID Alert is offline"

Issue : 
"COVID Alert is offline" screen is not displayed on phones that have a positive diagnosis. The "Thanks for helping fight COVID" screen is displayed instead.

**Comment by timarney** [comment]
This might be covered by 
https://github.com/cds-snc/covid-shield-mobile/pull/791

**Comment by nickmly** [comment]
@timarney This is fixed on the master branch. With Bluetooth on and airplane mode on I see the COVID Alert is offline screen.

**Comment by srepussard** [comment]
Tested on v62 : **Passed**
- This has been fixed
