### ISSUE TITLE
"COVID Alert is off" screen is not displayed when turned off EN manually on Android

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#679]
Environment : 
Pixel 3a, Android 10, v46 from Play Store

Scenario : 
- Use an Android phone
- Open app (in my test, I'm in a positive diagnosis state)
- Go to phone settings : Settings>Google>COVID-19 exposure notifications, and toggle off "Use Exposure Notifications"
- Return to the app

Expected : 
Since EN is turned off, COVID Alert should also be off and appropriate screens should be displayed

Issue : 
Instead of displaying "COVID Alert is off" screen, the "Thanks for helping fight COVID" screen remains.
Note that the menu does show "COVID Alert is off" and the option to turn on EN from the app is available

![Screenshot (Jul  14, 2020 09_29_50)](https://user-images.githubusercontent.com/47008295/87451410-aae2d900-c5b4-11ea-9c90-49aaaec44227.png)
![Screenshot (Jul  14, 2020 09_29_36)](https://user-images.githubusercontent.com/47008295/87451412-ac140600-c5b4-11ea-8096-4df1223b8642.png)

**Comment by JuliannaR** [comment]
@srepussard are you turning off EN notifications from the framework or from the app? You need to do both.

**Comment by srepussard** [comment]
> @srepussard are you turning off EN notifications from the framework or from the app? You need to do both.

I was not aware we can turn off EN via the app? But obviously here, when I turned off EN from the system, the app picked up on it since "COVID Alert is off" but the home screen doesn't reflect that

**Comment by srepussard** [comment]
Tested on v64 : **Passed**
- This has been fixed
