### ISSUE TITLE
Android S10 FR OS no exposure after 24hr (v47)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#681]
Samsung Galaxy S10 Android version 10
OS is set to French
UUID= Manon_S10 FR

July 13 @714am set device next to a positively diagnosed device  for +15 mins (1 foot apart)
home screen shows You're all set! (FR)
12:48pm - 20 exposure checks were done.

July 14 @614am 
home screen of app = You're all set (FR)
Exposure checks count now at 40 ... 20 checks were done at 614am
Updated the app version to 47
10:08am home screen shows no exposure detected (FR) 
last exposure check as @614am

positively diagnosed device iPhone XR EN iOS - UUID: Manon - iPhone 14

EDIT: On July 15 am checked phone again - no push notifications appeared on closed screen. 
app was already opened - msg on home screen: No exposure detected (fr)
reviewed the COVID Exposure checks (Google Settings) last check was done July 14 at 614am
Closed and re-opened the app
msg no exposure detected (FR) appears for 10s and then You may have been exposed (Fr) message is now displayed
reviewed the COVID Exposure checks - new checks appear @ 616am 20x.

**Comment by ndolter** [comment]
Samsung Galaxy version 8
OS is set to English
App ver = 49
UUID= Nat1And7


July 15 @ 8:45am set device (android ver 8) next to a positively diagnosed device (Samsung Galaxy, ver 7) for +15 mins (< 2 feet apart)
Expected result = After 24 hours a push notification is displayed on closed screen and msg on home screen = You may have been exposed
Actual Result = Neither message was received

**Comment by JuliannaR** [comment]
@mmiron-HC the UTC update from V50 will have fixed this. Could you retest and create a new issue if it's still an issue?
