### ISSUE TITLE
14 exposure checks at same time on Android after fresh install

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#683]
Environment : 
Pixel 3a, Android 10, v48 from Play Store

Scenario : 
- Do a fresh install
- Go through onboarding and turn on EN so that COVID Alert is active
- Leave the phone for a bit (took about 10-15 min for me I think)
- Check exposure logs on phone (Settings>Google>Exposure notifications>Exposure checks)

Expected : 
Not so sure...

Issue : 
There was 14 checks at once after a fresh install. That seems excessive especially if we have a limit per day.

![Screenshot (Jul  14, 2020 10_22_25)](https://user-images.githubusercontent.com/47008295/87457056-a4585f80-c5bc-11ea-8f7f-641185c9f80e.png)

**Comment by timarney** [comment]
https://github.com/cds-snc/covid-shield-mobile/issues/642

**Comment by JuliannaR** [comment]
@srepussard this is already being worked on in the issue that Tim linked above. So I'll close this one.
