### ISSUE TITLE
Next/Done Buttons Not working

### ISSUE THREAD

**Issue by mtamer** [cds-snc/covid-shield-mobile#684]
![intro](https://user-images.githubusercontent.com/5177678/87459935-0f645f00-c5da-11ea-8b47-066cd72bd3e4.png)

Buttons for intro not working. Unable to get passed Location page.

**Comment by timarney** [comment]
We tracked this down it will get fixed in the next build tonight.

**Comment by timarney** [comment]
Fixed in v49
