### ISSUE TITLE
Remove step 3 of 6 from the onboarding flow

### ISSUE THREAD

**Issue by Stephen-PM** [cds-snc/covid-shield-mobile#685]
Remove the step titled _What COVID Alert does not do_ from the app. We have determined that this information is causing more confusion than benefit.

This will also require changing the page numbering of each page. (for example, step 1 of 6 becomes step 1 of 5).

**Comment by JuliannaR** [comment]
@mtropper This will also impact the numbering in the Step X of X sequence.

**Comment by katewilhelm** [comment]
Also there's a fifth bullet added to the screen in Step 2 of 5 "Your privacy is safe"

Figma is up to date, and here's a screen shot 
<img width="459" alt="Screen Shot 2020-07-14 at 2 58 57 PM" src="https://user-images.githubusercontent.com/57191279/87465432-a208fc00-c5e2-11ea-97af-96a1ca614e54.png">

**Comment by timarney** [comment]
As those screens are being worked on - feel free to break out the text (ids) for the bold text.

As the start to:
https://github.com/cds-snc/covid-shield-mobile/issues/480

**Comment by timarney** [comment]
Merged.
