### ISSUE TITLE
Subsequent upload - Random IDs not being uploaded successfully (iPhone) 

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#696]
iPhone 8 
this is day 6 (?) of the phone being positively diagnosed. Every other day, I have been able to share codes without issue.
After updating to version 49, I'm am no longer able to upload random IDs successfully. I was able to successfully share my random IDs on v47 of Android (OnePlus3) this morning.

from the home screen, click Upload your random codes button
Click Agree on the now you can upload your codes window.
Random codes could not be uploaded - you did not give permission is displayed - click OK

COVID Exposure Notifications = ON
Bluetooth = On
Notificaitons = On
Location = on

**Comment by timarney** [comment]
iOS

> After updating to version 49, I'm am no longer able to upload random IDs successfully. I was able to successfully share my random IDs on v47 of Android (OnePlus3) this morning.

☝️ 

@emilykuret 
@JuliannaR

**Comment by timarney** [comment]
@dsamojlenko is pushing up a new build.

**Comment by mmiron-HC** [comment]
v50 is now working.
