### ISSUE TITLE
Exposure checks stopped on iPhone 8 after it was positively diagnosed on July 10 (iOS)

### ISSUE THREAD

**Issue by mmiron-HC** [cds-snc/covid-shield-mobile#697]
iPhone 8
COVID Exposure Notifications = on
Bluetooth = on
Notifications = on

Entered a valid diagnosis code on July 10th
the count down rolls through each day, now at Day 6 
Verified the Exposure checks (Privacy > Health >Covid 19 Exposure Logging 
Under the COVID Alert Active app it says that COVID Alert has checked your log of collected random IDs 0 times.
Click Exposure Checks.
It displays the list of exposure checks. Last updated was July 10 at 647am (20x)
can't give you the UUID since I can't access the demo menu.

Expected behaviour: daily checks would still be occurring
![IMG_1814](https://user-images.githubusercontent.com/65728700/87550275-e517ad80-c67c-11ea-9a69-46d07ef3a379.PNG)
![IMG_1816](https://user-images.githubusercontent.com/65728700/87550291-e77a0780-c67c-11ea-9986-23b1b79fb90d.PNG)
![IMG_1815](https://user-images.githubusercontent.com/65728700/87550305-e9dc6180-c67c-11ea-82dc-76111319c88c.PNG)

**Comment by JuliannaR** [comment]
@timarney @henrytao-me should exposure checks still run in this instance?

**Comment by timarney** [comment]
My understanding is this is expected.

cc: @henrytao-me

**Comment by JuliannaR** [comment]
This looks to be expected behaviour as the phone changed from checking for potential exposures to being in a disagnosed state.I think we can close this one @mmiron-HC and I discussed in the testing sync yesterday.

**Comment by henrytao-me** [comment]
In `diagnosed` status, there will be no calls to the framework, hence no exposure checks. 

Close as non issue. 🙇
