### ISSUE TITLE
Back button is missing in landscape orientation

### ISSUE THREAD

**Issue by paulettefrancis** [cds-snc/covid-shield-mobile#698]
When on the Ontario COVID-19 Test Results page in landscape orientation, the back button for "COVID Alert" is missing, so a user in unable to go back to the COVID Alert app.

Tested on iPhone XR 13.5.1

P.S. Come to think of it, this is a Gov of Ontario issue I believe, but I'll record issue anyway.

![Portrait](https://user-images.githubusercontent.com/22638158/87552972-658bdd80-c680-11ea-8376-c755e49bb15d.jpg)
![Landscape](https://user-images.githubusercontent.com/22638158/87552987-6a509180-c680-11ea-8a69-bafe4242c519.jpg)

**Comment by JuliannaR** [comment]
Combined landscape issues https://github.com/cds-snc/covid-shield-mobile/issues/701
