### ISSUE TITLE
Text gets cut off in landscape orientation

### ISSUE THREAD

**Issue by paulettefrancis** [cds-snc/covid-shield-mobile#699]
On the "How it works" set of pages, when in landscape orientation, the text gets cut off.  

It looks like the font size has to be changed as this is the way it's appears on pages that don't have this issue.

Tested on iPhone XR 13.5.1

![font](https://user-images.githubusercontent.com/22638158/87555554-99b4cd80-c683-11ea-8815-c8f3c167e757.jpg)

**Comment by JuliannaR** [comment]
Combined landscape issues here: https://github.com/cds-snc/covid-shield-mobile/issues/701
