### ISSUE TITLE
new screen between splash screen and onboarding

### ISSUE THREAD

**Issue by JuliannaR** [cds-snc/covid-shield-mobile#700]
We have added a new screen between the splash screen and onboarding this screen will have language selection options to meet official language requirements and better orient users who load the app.

<img width="233" alt="Screen Shot 2020-07-15 at 11 08 21 AM" src="https://user-images.githubusercontent.com/35537308/87562413-003de980-c68c-11ea-8f1c-fad4164bcbdc.png">

**Comment by timarney** [comment]
1) Will the in app language toggle in the bottom drawer come back again now?

**Comment by JuliannaR** [comment]
@amazingphilippe @katewilhelm thoughts on this?

**Comment by katewilhelm** [comment]
Yes I think the in-app toggle in the menu would come back. Unless there's a reason it can't or shouldn't?

**Comment by amazingphilippe** [comment]
> Will the in app language toggle in the bottom drawer come back again now?

Yes

**Comment by JuliannaR** [comment]
I think it should as well, because we offer the choice to select a language we need to enable users to change it back.

**Comment by timarney** [comment]
Added a ref https://github.com/cds-snc/covid-shield-mobile/issues/653

<img width="235" alt="87562123-96bddb00-c68b-11ea-929c-4fb2ac535569" src="https://user-images.githubusercontent.com/62242/87576727-cbd42880-c69f-11ea-9bca-b8d5013d33a2.png">

**Comment by mtropper** [comment]
This gives a much better user experience :)

**Comment by timarney** [comment]
PT 1 of 2

https://github.com/cds-snc/covid-shield-mobile/pull/713

**Comment by timarney** [comment]
WIP https://github.com/cds-snc/covid-shield-mobile/pull/716

**Comment by amazingphilippe** [comment]
Part 2 of 2 is giving me trouble. Dropping #726 in here if anyone can have a look

**Comment by mtropper** [comment]
@amazingphilippe I added a commit to your branch. Try it now
