### ISSUE TITLE
Add design principles?

### ISSUE THREAD

**Issue by RByers** [cds-snc/covid-shield-mobile#71]
Thanks so much for iterating on CovidShield in public, the transparency is awesome!

I find the [original rationale document](https://github.com/CovidShield/rationale/blob/master/README.md) to be helpful in understanding the design priorities. As an eventual user who is a software developer, understanding the principles behind the app design is important to me. But it would also be important for any potential contributor.

Have these principles changed at all with the move from the Shopify project to CDS? If not, I'd be happy to submit a PR to bring a copy of that document into this repo so it could be maintained here. WDYT?

**Comment by timarney** [comment]
cc:

@sboots 
@Stephen-PM

**Comment by timarney** [comment]
Thanks for reaching out @RByers I've noted this to some CDS folks and we'll see what they come back with :)

@katewilhelm

**Comment by RByers** [comment]
Thanks. Or maybe I'm just confused on the relationship between the two projects? When I wrote this I assumed this project largely superseded the CovidShield one, but now I see some patches are continuing to land upstream. So maybe the relationship could just be clarified so interested folks like me know where to watch?

**Comment by timarney** [comment]
For clarity - the National app will be released with the code / content from this repo.  We will continue to pull upstream changes from the Covid Shield app i.e. for bug fixes.

**Comment by timarney** [comment]
>Have these principles changed at all with the move from the Shopify project to CDS? If not, I'd be happy to submit a PR to bring a copy of that document into this repo so it could be maintained here. WDYT?

@Stephen-PM can you confirm with the team ?

**Comment by timarney** [comment]
Going to close this.  The team is aware and will reach as needed.
