### ISSUE TITLE
"You have been exposed" push notification keeps showing up

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#724]
Environment : 
Exposed phone : Pixel 3a, Android 10, v49 from Play Store
Diagnosed phone : iPhone 8, v50 TestFlight

Scenario : 
- Pre-conditions : have one diagnosed phone (iPhone in my test) and one non-infected phone (this Android) in close proximity together for a while
- Check exposed state/checks regularly

Expected : 
There should be exposure checks regularly by the non-infected phone (in the background) and after exposure, there should be a "You have been exposed" notification (once only) that guides the user back to the app for further steps

Issue : 
The "You have been exposed" notification keeps popping up : I have seen it 3 times in the span of half a day
- First exposure message : July 15th at 18:41, one match among 2 exposure checks
- Second exposure message : July 15th at 22:10, 2 matches among 2 exposure checks
- Third exposure message : July 16th at 06:48, 1 match among 2 exposure checks
(I can give you more details and more history after this, just ask me in comments)

|  ![Screenshot (Jul  15, 2020 18_47_34)](https://user-images.githubusercontent.com/47008295/87681975-24ed9c00-c734-11ea-88a9-58496768c730.png)  |  ![Screenshot (Jul  15, 2020 18_48_56)](https://user-images.githubusercontent.com/47008295/87681980-26b75f80-c734-11ea-9152-18aa1b35b815.png)  |  ![Screenshot (Jul  15, 2020 22_10_20)](https://user-images.githubusercontent.com/47008295/87681981-274ff600-c734-11ea-8bcf-9cd00b1b945f.png)  |  ![Screenshot_20200715-221118](https://user-images.githubusercontent.com/47008295/87681985-28812300-c734-11ea-88bb-c2e368564cfc.png)  |  ![Screenshot_20200715-221126](https://user-images.githubusercontent.com/47008295/87681986-28812300-c734-11ea-9477-db49860f0f9a.png)  |
| ------------- |:-------------:| -----:|-------------:|-------------:|

**Comment by henrytao-me** [comment]
@timarney Does v49 have the fix that @jeberhardt did?

**Comment by henrytao-me** [comment]
@srepussard Sorry, I formatted your ticket description 🙇

**Comment by henrytao-me** [comment]
I believe it is fixed from this PR https://github.com/cds-snc/covid-shield-mobile/pull/705. Build 49 was released on Jul 14, 7:17 PM. 

I close this for now. Please reopen if this happens again on v51 or newer.

**Comment by srepussard** [comment]
I confirm that since I upgraded to v51+, it didn't happen again in the span of one full day.
