### ISSUE TITLE
UTC vs device local time - testing / edge cases

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-shield-mobile#740]
Now that we've moved to UTC we need ensure we've tracked edge cases

> Note: we should continue looking into UTC VS device timezone to find all race conditions that could mess up user experience. 

https://github.com/cds-snc/covid-shield-mobile/issues/676#issuecomment-659095038

**Comment by henrytao-me** [comment]
![image](https://user-images.githubusercontent.com/5274722/87976134-9910a280-ca9a-11ea-9969-26c5b8df1d4e.png)


More details https://docs.google.com/document/d/1ip3hnQqLjUy0ayMzFrn8SNZjfYtRehnuzdMiV6V2Fpo/edit#

**Comment by henrytao-me** [comment]
Close as no action needed, reopen later if necessary
