### ISSUE TITLE
Add in screen to onboarding

### ISSUE THREAD

**Issue by emilykuret** [cds-snc/covid-shield-mobile#752]
Screen will be step 4 of 6 for onboarding
new illustration

**Comment by katewilhelm** [comment]
English and French text are ready 
<img width="336" alt="Screen Shot 2020-07-17 at 2 42 31 PM" src="https://user-images.githubusercontent.com/57191279/87820290-d297a280-c83b-11ea-986d-29ab36773f9d.png">

**Comment by mtropper** [comment]
@emilykuret @amazingphilippe  where can I find the image ALT text?
