### ISSUE TITLE
Drawer menu scrolling - Android

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-shield-mobile#774]
Internal test build:

**Bottom drawer scrolling:**
<img width="300" src="https://user-images.githubusercontent.com/62242/87837562-ed7d0d80-c861-11ea-979a-b46532d9cff7.png">

@JuliannaR I believe this is a regression.

**Comment by JuliannaR** [comment]
Yes, focus jumps to the bottom of the drawer here too.

**Comment by timarney** [comment]
Checked against the beta build and the menu as far as scrolling acts the same.

**Comment by JuliannaR** [comment]
There is some lag with lower powered devices, two finger gesture, read all work consistently, talkback has some issues if users swipe too quickly left to right to move though content individually. 
We can research if there are ways to optimize this experience, but am okay to close for now as it is functioning.
