### ISSUE TITLE
Turn on Bluetooth button doesn't work

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/covid-shield-mobile#78]
If bluetooth is turned off globally, the button should take you to the correct screen to turn it on.

**Comment by ChrisDryden** [comment]
I was doing some research into the linking to the bluetooth page and came across some projects that opened up the right links for bluetooth:

This is the line that needs to be changed: https://github.com/cds-snc/covid-shield-mobile/blob/cb3f1a75492e368eb390d2c4b61574c9757d19a5/src/screens/home/views/BluetoothDisabledView.tsx#L11


Heres an example for IOS: https://github.com/rjblopes/react-native-device-settings/pull/8/files

Heres an example for Android: https://github.com/LuoZihYuan/Synesthesia-Experiment/blob/6149fff0f2e2d7c54bd6dad89bbc725f0e9bf6fa/Runtime/SERoboArm.js#L36

I am testing this out now

**Comment by timarney** [comment]
Nice, thanks so much for looking into this for us.

**Comment by timarney** [comment]
Was looking at the use of `App-prefs:root=Bluetooth`

And not sure if it's still the case but it might get rejected.

https://developer.apple.com/forums/thread/100471

```
Guideline 2.5.1 - Performance - Software Requirements

Your app uses the "prefs:root=" non-public URL scheme, which is a private entity. The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.
 
```

<img width="920" alt="Screen Shot 2020-06-20 at 8 04 41 PM" src="https://user-images.githubusercontent.com/62242/85213804-6fe0e300-b331-11ea-9b12-ba53d0ffcf48.png">

**Comment by timarney** [comment]
https://github.com/CovidShield/mobile/issues/125#issuecomment-647055105

Found this note 

```
These functions are disabled by default. You must not call them If your app need submit to App Store. As an alternative, you can show a tip to tell the user how to change the system setting.
```

https://github.com/c19354837/react-native-system-setting/blob/master/iOS.md#ios

<img width="984" alt="Screen Shot 2020-06-20 at 8 19 39 PM" src="https://user-images.githubusercontent.com/62242/85213978-7e2ffe80-b333-11ea-882b-c99ea877190f.png">

**Comment by ChrisDryden** [comment]
It appears on iOS it will not be possible to open up the bluetooth settings, we will just have to have a link saying enable bluetooth.

**Comment by timarney** [comment]
@smcmurtry 

Via @Stephen-PM 
> We'll remove the button at least temporarily

**Comment by ChrisDryden** [comment]
The main issue apart from this which was referenced in the link earlier is that there is actually no check for if bluetooth in enabled anywhere. The closest thing I could find was this which appears to be compatible with iOS and allows you to perform the switch for android too. 
https://github.com/solinor/react-native-bluetooth-status

**Comment by timarney** [comment]
https://github.com/cds-snc/covid-shield-mobile/blob/5c36b2582eb4e60963e991fce97d772c03880e20/ios/CovidShield/ExposureNotification.m#L98

**Comment by ChrisDryden** [comment]
My apologies, I am fairly new to objective c, I thought that this was a case switch for an not yet completed function but I now see this is being returned by the native exposure notification system. 

I couldn't find an equivalent of that case in the android portion. I am new to that syntax in objective c but it appears to me that this case switch can't distinguish the case where it's inactive and that the bluetooth is off.

**Comment by timarney** [comment]
No worries - we're all getting up to speed on the codebase :)

And yes sounds like that's the case.

**Comment by ChrisDryden** [comment]
Added a PR with a potential solution to the bluetooth status check and the ability to change the bluetooth settings in app for android ^

Also attaching this issue from CovidShield here for reference: https://github.com/CovidShield/mobile/issues/121

**Comment by henrytao-me** [comment]
Ref https://github.com/cds-snc/covid-shield-mobile/issues/78

**Comment by smcmurtry** [comment]
We've removed the bluetooth button since it isn't actually possible to direct the user to the global bluetooth settings page on ios. Instead we have this screen now:

<img width="413" alt="Screen Shot 2020-06-21 at 4 19 46 PM" src="https://user-images.githubusercontent.com/5498428/85236426-087f6d80-b3db-11ea-896a-f555252338ef.png">
