### ISSUE TITLE
Code entry - No network connection

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-shield-mobile#786]
The app currently allows entering a code when the device doesn't have an internet connection.

@JuliannaR should we hide the entry box in this case or display a message.

The primary screen handles the connection type properly but the code entry box is still available.

**Comment by obrien-j** [comment]
This should probably be broadened out to, "disallow code submission without an active network connection", as designed now, it appears the code submission is failing and may lead to support calls, and/or folks giving up because they don't think they can type the code in properly.

**Comment by timarney** [comment]
@emilykuret to reach out to the content team.

**Comment by timarney** [comment]
**No internet connection**
<img width="200" src="https://user-images.githubusercontent.com/62242/88061020-f6f1c880-cb34-11ea-9414-4ba51479e41f.jpg"> 

**Enter a code** 
(you can't do this with a connection)

<img width="200" src="https://user-images.githubusercontent.com/62242/88061021-f78a5f00-cb34-11ea-8dd9-1a5f89cb4c1b.jpg">

**Comment by timarney** [comment]
<img width="500" alt="Screen Shot 2020-07-21 at 3 58 46 PM" src="https://user-images.githubusercontent.com/62242/88100879-32a78500-cb6b-11ea-8042-bc6178850b7d.png">

**Comment by timarney** [comment]
https://github.com/cds-snc/covid-shield-mobile/pull/824
