### ISSUE TITLE
Debug menu: create a way to get to "diagnosed, x days later" state

### ISSUE THREAD

**Issue by smcmurtry** [cds-snc/covid-shield-mobile#79]
This will give us a way to work on this page.

**Comment by timarney** [comment]
@maxneuvians @dsamojlenko 

I would like to get away from using the debug menu.  My concern is we end up getting the app into states that the real app can't end up in.

It would be nice if we can hit the api via a terminal command via curl request to 

- Trigger push Notifications 
- Exposure state (re-confirm state)

**Comment by timarney** [comment]
Will revisit.
