### ISSUE TITLE
Upload new random codes notification should not come on code entering day

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#792]
Environment : 
Pixel 3a, Android 10, v53 from Play Store

Scenario : 
- I installed the app and entered a positive diagnosis code on the same day around 1pm and I was prompted to share random codes at that step as expected
- Around 6pm, I received a push notification about "Upload new random codes" on the phone and clicking on it led me through the usual code sharing screens

Issue : 
I was prompted to share codes twice in one day
Note that this did not affect the days countdown

**Comment by timarney** [comment]
@henrytao-me any thoughts?

**Comment by henrytao-me** [comment]
This is expected as I outline here https://github.com/cds-snc/covid-shield-mobile/issues/740#issuecomment-661277970.

**Comment by henrytao-me** [comment]
Close for now and reopen if we decide to change.

**Comment by srepussard** [comment]
I updated the test cases to adapt to this. Thank you.
