### ISSUE TITLE
Page continues to read the previous/closed page image

### ISSUE THREAD

**Issue by qanitah** [cds-snc/covid-shield-mobile#799]
With VoiceOver on, when the user is going item by item from How it works (step 3 of 6) to "Learn more about how it works" and comes back to step 3 by either clicking Close or by going through all 4 of it's tabs, it announces "Hand drawn illustration of mobile phone in a pocket. sending and receiving signals". It announces first when the user gets back and then continues to announce this when the user swipes right to read next item.

This is also the case for Step 5 for "Learn more about privacy". VoiceOver continues to announce "Privacy policy heading".

Please see video of the Step 3. I'm only swiping right and left. https://photos.app.goo.gl/TCFbUyq7SPJQM1WZ6

iOS 13.5.1 on iPhone 7

**Comment by JuliannaR** [comment]
@mtropper can you take a look at this one?

**Comment by mtropper** [comment]
@JuliannaR  this appears to be a bug that was introduced in Version 54. its not limited to these screens it happens in all of the screens that are opened in the overlay window as well. Do we know what change was made in that release?

**Comment by mtropper** [comment]
I tested and It work properly in V53 and got broken in V54 on testflight

**Comment by JuliannaR** [comment]
I think this is introduced when fixing for android focus. @smcmurtry do you remember something about Android and IOS having different approaches to focus? This might related to https://github.com/cds-snc/covid-shield-mobile/pull/766

**Comment by smcmurtry** [comment]
I was also able to reproduce this going from the bottom menu to the "Change province or territory" screen and then clicking close. Focus is stuck on the "Province or territory" heading, which is offscreen after the page is closed.

This is due to the navigator change from #738. I ran `git checkout f71d7aab38b64022e569098b1d70eb423846b300 src/navigation/MainNavigator.tsx` to get the old navigator and this issue went away. 

I'm not sure how to fix this - there is a [`useFocusEffect`](https://reactnavigation.org/docs/navigation-lifecycle) hook we can use with the new navigator, which we could use to do something with the autofocus when the page changes.

**Comment by nickmly** [comment]
I made a PR for the how it works screen and privacy screen specifically and it is working on Android: #801. It uses a `useEffect` hook to manually focus on an element when the navigator focuses on a screen (or when an overlay window is closed)

**Comment by mtropper** [comment]
@nickmly unfortunately the same issue continues in IOS. I reverted the changes from pull 738 (https://github.com/cds-snc/covid-shield-mobile/pull/738/commits/651ce631b81b7485479e7c1752add86ffb18d9ea) and things started to work as @smcmurtry but reverting made the fix you had made for Android to stop working.

**Comment by henrytao-me** [comment]
Note: I think there are 3 problems here:
1. react-native-screen causes the main issue described in the ticket which is: VoiceOver / TalkBack reads screen that are being unmounted. Look like react-native-screen doesn't unmount it. It just hides the screen.
=> Suggestion for now: remove react-native-screen

2. src/screens/tutorial/views/ItemView.tsx  which is used for Tutorial screen. When pressing on close button, it's unmount > mount > unmount. This is the main problem that causing the iOS that I describe above.
=> Suggestion: keep digging to see why this happens.

3. AccessibilityInfo.isScreenReaderEnabled() is async + we have 200ms delay to start reading which introduce more delay. If two elements on the screen requesting for focus, it's unpredictable which one will take over. This is not likely to happen in theory as we set which element to auto focus on each screen. However, if 2nd case happens, then this happens.
=> Suggestion: in src/shared/useAccessibilityAutoFocus.ts
Replace AccessibilityInfo.isScreenReaderEnabled()  by using useAccessibilityService as we have a provider for it. So, we can get the enabled result instantly. 
Replace delay function by queue function. The idea is that if we have more than one element requesting autofocus, after the timeout (200ms or whatever), the most recent element requesting focus will be read. The rest will be ignored. 

cc @smcmurtry @nickmly
