### ISSUE TITLE
Background Task elevated priority not using .exposure-notification special terminator

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/covid-shield-mobile#81]
Just flagging this as it came up in the Shopify channel about potentially not leveraging one of the elevated priority flags for background tasks.

Might be worth running this by Apple to ensure we're leveraging the tooling they provide effectively.

https://github.com/cds-snc/covid-shield-mobile/blob/2e6dc8f776a625024a0f1aad68861a281959ec72/ios/CovidShield/Info.plist#L7

https://developer.apple.com/documentation/exposurenotification/building_an_app_to_notify_users_of_covid-19_exposure

"Create a Background Task to Check for Exposure
The app uses a background task to periodically check whether the user may have been exposed to an individual with COVID-19. The app’s Info.plist file declares a background task named com.example.apple-samplecode.ExposureNotificationSampleApp.exposure-notification. The BackgroundTask framework detects apps that contain the Exposure Notification entitlement and a background task that ends in exposure-notification. The operating system automatically launches these apps when they aren’t running and guarantees them more background time to ensure that the app can test and report results promptly."

**Comment by obrien-j** [comment]
Addressed in #354

**Comment by obrien-j** [comment]
cc: @timarney I'm not entirely sure how to validate this completion, so I'll leave it with you to close.

**Comment by timarney** [comment]
Code merged in 354 - we can adjust as need be.
```
BackgroundFetch.scheduleTask({taskId: BACKGROUND_TASK_ID, delay: 0, periodic: true});
```
