### ISSUE TITLE
Enter code - Submit button enabled after only 8 char entered

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#835]
Environment : 
Pixel 3a, Android 10, v62

Scenario : 
- Navigate to the "Enter a one time key" screen
- Start entering a key

Expected : 
The app now requires a 10-digit key so the "Submit" button should only be enabled after the user enters 10 char

Issue : 
The Submit button is enabled after only 8 char

![Screenshot (Jul  22, 2020 08_07_34)](https://user-images.githubusercontent.com/47008295/88193760-e56ef600-cbf2-11ea-9bb4-584121af7d28.png)

**Comment by nickmly** [comment]
Fixed in #840

**Comment by srepussard** [comment]
Tested on v64 : **Passed**
- Maximum length of field is now 12 char and Submit is enabled after 10 char
