### ISSUE TITLE
Android app notification settings - "CovidShield" is still displayed

### ISSUE THREAD

**Issue by srepussard** [cds-snc/covid-shield-mobile#836]
Environment : 
Pixel 3a, Android 10, v62

Scenario : 
- Install the app
- Navigate to the app notification settings on your Android phone (Settings>Apps and notifications>COVID Alert>Notifications)

Issue : 
"CovidShield" is still displayed

![Screenshot (Jul  22, 2020 07_46_58)](https://user-images.githubusercontent.com/47008295/88194311-88c00b00-cbf3-11ea-9b60-39a1ffde5354.png)

**Comment by henrytao-me** [comment]
PR is up. When testing new build, you can expect:
- See both CovidAlert and CovidShield if you upgrade. 
- See only CovidAlert if you reinstall.

cc @srepussard

**Comment by srepussard** [comment]
Tested on v64 : **Passed**
- This has been fixed

![Screenshot (Jul  23, 2020 11_22_34)](https://user-images.githubusercontent.com/47008295/88323339-ef6a2500-ccd6-11ea-836b-f59e3e293979.png)
