### ISSUE TITLE
Use device locale

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-shield-mobile#91]
It appears that the app will always default to English. 

Need to look into use the device language.

This link mentions using React "Native Modules"
https://stackoverflow.com/questions/33468746/whats-the-best-way-to-get-device-locale-in-react-native-ios

```javascript
import { NativeModules } from 'react-native'

// iOS:
const locale = NativeModules.SettingsManager.settings.AppleLocale // "fr_FR"

// Android:
const locale = NativeModules.I18nManager.localeIdentifier // "fr_FR"

```

It appears that's no longer available in iOS 13

https://github.com/facebook/react-native/issues/26606

The suggested workaround is:

```javascript
const getDeviceLocale = () => {
  if (Platform.OS === 'ios') {
    let locale = NativeModules.SettingsManager.settings.AppleLocale // "fr_FR"
    if (locale === undefined) {
        // iOS 13 workaround, take first of AppleLanguages array  ["en", "en-NZ"]
        locale = NativeModules.SettingsManager.settings.AppleLanguages[0];
        if (locale) {
          return locale;
        }
    }
  }

  if (Platform.OS === 'android') {
    return NativeModules.I18nManager.localeIdentifier;
  }

  return 'pt-BR';
}; 
```

**Current**

<img width="500" alt="Screen Shot 2020-06-21 at 4 11 11 AM" src="https://user-images.githubusercontent.com/62242/85219949-cf60e200-b375-11ea-9063-9b1780ff5b63.png">

<hr>

<img width="500" alt="Screen Shot 2020-06-21 at 4 11 41 AM" src="https://user-images.githubusercontent.com/62242/85219955-d7b91d00-b375-11ea-8f3b-79839cd4ba3e.png">

**Comment by timarney** [comment]
Upstream issue here:
https://github.com/CovidShield/mobile/issues/111

**Comment by timarney** [comment]
@Stephen-PM if this doesn't get fixed upstream can we mark this to be handled in a v2 release?

**Comment by henrytao-me** [comment]
Merged!

**Comment by timarney** [comment]
Thanks @henrytao-me will hopefully get this pulled back today.
