### ISSUE TITLE
Language & Province drawer menu selection

### ISSUE THREAD

**Issue by timarney** [cds-snc/covid-shield-mobile#96]
When selecting a language or a province the menu "auto" closes and slides back up.

![bottom-menu](https://user-images.githubusercontent.com/62242/85222011-73528980-b386-11ea-986b-e12ad16783b1.gif)

**Comment by timarney** [comment]
We're using the initial province select from upstream + have added to the drawer menu (https://github.com/cds-snc/covid-shield-mobile/issues/96#issue-642535054)

Also here:

<img width="250" alt="Screen Shot 2020-06-21 at 6 21 45 AM" src="https://user-images.githubusercontent.com/62242/85222255-b5c89600-b387-11ea-98e3-4ca34d16f164.png">


Noting the upstream.



**Upstream** 
https://github.com/CovidShield/mobile/issues/81

**Comment by henrytao-me** [comment]
<img src="https://user-images.githubusercontent.com/5274722/85231122-aa469080-b3c2-11ea-9287-0d6087aedea9.gif" width="240" />

<img src="https://user-images.githubusercontent.com/5274722/85231125-aca8ea80-b3c2-11ea-80c3-f97b7068e8ec.gif" width="240" />

**Comment by henrytao-me** [comment]
I cannot find iOS 13.5.1 for some reason, still updating my Xcode and verify again. I will move to other ticket for now.

**Comment by timarney** [comment]
@henrytao-me 

Tried on my device via TestFlight with the Covid Shield app as well.


![shield](https://user-images.githubusercontent.com/62242/85233769-e5eb5580-b3d6-11ea-96e7-a268ca67d646.gif)

**Comment by timarney** [comment]
Tested via the Android simulator.  The click result is slow and the menu flashes.

@jeffmaher can you maybe confirm on a device? 

![android](https://user-images.githubusercontent.com/62242/85234766-cd326e00-b3dd-11ea-8b86-bd8e07addc06.gif)

**Comment by jeffmaher** [comment]
> Tested via the Android simulator. The click result is slow and the menu flashes.
> 
> Maybe it's because of debug mode?
> 
> @jeffmaher can you maybe confirm on a device?
> 
> ![android](https://user-images.githubusercontent.com/62242/85234766-cd326e00-b3dd-11ea-8b86-bd8e07addc06.gif)

Still waiting on device to arrive in the mail. Will try if it arrives tomorrow, although I think @dsamojlenko might have snagged one today.

**Comment by timarney** [comment]
@Stephen-PM we're trying to confirm why we're seeing this and @henrytao-me using our version isn't.

**Comment by timarney** [comment]
Fixed upstream :)
